---
sidebar: sidebar 
permalink: concept_import_from_dashboard_gallery.html 
summary: 'Vous pouvez importer les tableaux de bord recommandés pour répondre aux questions d"analyse de l"activité.' 
keywords: dashboard, gallery, import 
---
= Importation à partir de la galerie de tableaux de bord
:allow-uri-read: 


[role="lead"]
Cloud Insights fournit un certain nombre de tableaux de bord recommandés pour vous fournir des informations stratégiques sur vos données. Chaque tableau de bord contient des widgets conçus pour répondre à une question spécifique ou résoudre un problème particulier lié aux données actuellement collectées dans votre environnement.

Pour importer un tableau de bord à partir de la galerie, procédez comme suit :

. Sélectionnez *Tableau de bord > Afficher tous les tableaux de bord*
. Cliquez sur *+dans Galerie*
+
Une liste de *tableaux de bord recommandés* s'affiche. Chaque tableau de bord est nommé avec une question spécifique que le tableau de bord peut vous aider à résoudre. Des tableaux de bord permettent de répondre aux questions concernant différents types d'objets, notamment AWS, NetApp, le stockage, VMware, et autres

. Sélectionnez un ou plusieurs tableaux de bord dans la liste et cliquez sur *Ajouter tableaux de bord*. Ces tableaux de bord s'affichent à présent dans votre liste de bord.


En plus des tableaux de bord recommandés, vous pouvez également choisir d'importer *tableaux de bord supplémentaires* qui ne sont pas pertinents pour vos données actuelles. Par exemple, si aucun collecteur de données de stockage n'est actuellement installé mais que vous prévoyez de le configurer ultérieurement, vous pouvez toujours choisir d'importer les tableaux de bord pertinents pour le stockage. Ces tableaux de bord seront disponibles à l'affichage mais ne peuvent pas afficher les données pertinentes tant qu'au moins un collecteur de données de stockage n'est pas configuré.
