---
sidebar: sidebar 
permalink: concept-worm.html 
keywords: worm, write once, read many, snaplock, retain, retention, period, cloud worm, worm storage, tiering 
summary: 'Vous pouvez activer le stockage WORM (écriture unique) en lecture seule sur un système Cloud Volumes ONTAP pour conserver les fichiers sous forme non modifiée pendant une période de conservation spécifiée. Le stockage WORM dans le cloud est optimisé par la technologie SnapLock, ce qui signifie que les fichiers WORM sont protégés au niveau des fichiers.' 
---
= Stockage WORM
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez activer le stockage WORM (écriture unique) en lecture seule sur un système Cloud Volumes ONTAP pour conserver les fichiers sous forme non modifiée pendant une période de conservation spécifiée. Le stockage WORM dans le cloud est optimisé par la technologie SnapLock, ce qui signifie que les fichiers WORM sont protégés au niveau des fichiers.



== Fonctionnement du stockage WORM

Une fois qu'un fichier a été alloué au stockage WORM, il ne peut pas être modifié, même après l'expiration de la période de conservation. Une horloge inviolable détermine le moment où la période de conservation d'un fichier WORM s'est écoulée.

Une fois la période de conservation écoulée, vous êtes responsable de la suppression des fichiers dont vous n'avez plus besoin.



== Chargement

La charge du stockage WORM est horaire, selon la capacité totale provisionnée des volumes WORM.

Disponible pour les conditions d'engagement PAYGO ou annuelles uniquement, la licence pour WORM peut être achetée sur le marché du fournisseur cloud. WORM prend en charge les modèles de licence basés sur les nœuds et les capacités.


NOTE: Les licences BYOL ne sont pas disponibles pour le stockage WORM sur Cloud Volumes ONTAP.

Vous devez comprendre le comportement de charge suivant avec Cloud Volumes ONTAP 9.10.1 et versions ultérieures :

* Depuis ONTAP 9.10.1, des volumes WORM et non-WORM peuvent exister sur le même agrégat.
* Si vous activez WORM lorsque vous créez un environnement de travail Cloud Volumes ONTAP, tous les volumes que vous créez à partir de BlueXP sont compatibles WORM. Toutefois, vous pouvez utiliser l'interface de ligne de commandes ou System Manager ONTAP pour créer des volumes dont le protocole WORM est désactivé. Ces volumes ne sont pas facturés au taux WORM.
* Si vous n'activez pas WORM lorsque vous créez un environnement de travail, le mode WORM est désactivé pour chaque volume créé à partir de BlueXP. Vous n'êtes pas facturé au débit WORM pour ces volumes.


https://cloud.netapp.com/pricing["En savoir plus sur la tarification pour le stockage WORM"^]



== Activation du stockage WORM

La façon dont vous activez le stockage WORM dépend de la version de Cloud Volumes ONTAP que vous utilisez.



=== Version 9.10.1 et ultérieure

Depuis Cloud Volumes ONTAP 9.10.1, vous pouvez activer ou désactiver WORM au niveau du volume.

Lorsque vous créez un environnement de travail Cloud Volumes ONTAP, vous êtes invité à activer ou désactiver le stockage WORM :

* Si vous activez le stockage WORM lors de la création d'un environnement de travail, le mode WORM est activé pour chaque volume créé à partir de BlueXP. Toutefois, vous pouvez utiliser System Manager ou l'interface de ligne de commandes pour créer des volumes dont le protocole WORM est désactivé.
* Si vous désactivez le stockage WORM lors de la création d'un environnement de travail, tous les volumes que vous créez à partir de BlueXP, System Manager ou de l'interface de ligne de commande sont désactivés. Si vous souhaitez activer WORM sur un environnement de travail Cloud Volumes ONTAP qui n'a pas été activé lors de la création, vous devez créer un ticket de support auprès du support NetApp.


Quelle que soit l'option choisie, vous devez <<Chargement,comprendre le fonctionnement de la charge>>.



=== Version 9.10.0 et antérieure

Vous pouvez activer le stockage WORM sur un système Cloud Volumes ONTAP lorsque vous créez un nouvel environnement de travail. Chaque volume que vous créez à partir de BlueXP est doté de la technologie WORM. Vous ne pouvez pas désactiver le stockage WORM sur des volumes individuels.



== Validation de fichiers sur WORM

Vous pouvez utiliser une application pour valider des fichiers sur WORM via NFS ou CIFS, ou utiliser l'interface de ligne de commande ONTAP pour auto-valider des fichiers sur WORM automatiquement. Vous pouvez également utiliser un fichier WORM inscriptible pour conserver les données écrites de façon incrémentielle, comme les informations de journal.

Après avoir activé le stockage WORM sur un système Cloud Volumes ONTAP, vous devez utiliser l'interface de ligne de commande ONTAP pour toute la gestion du stockage WORM. Pour obtenir des instructions, reportez-vous à la section http://docs.netapp.com/ontap-9/topic/com.netapp.doc.pow-arch-con/home.html["Documentation ONTAP"^].



== Suppression des fichiers WORM

Vous pouvez supprimer des fichiers WORM pendant la période de conservation à l'aide de la fonction de suppression privilégiée.

Pour obtenir des instructions, reportez-vous à la section https://docs.netapp.com/us-en/ontap/snaplock/delete-worm-files-concept.html["Documentation ONTAP"^]



== WORM et Tiering des données

Lorsque vous créez un nouveau système Cloud Volumes ONTAP 9.8 ou une version ultérieure, vous pouvez activer à la fois le Tiering et le stockage WORM. L'activation du Tiering des données avec le stockage WORM vous permet de transférer les données vers un magasin d'objets dans le cloud.

Voici les éléments à prendre en compte concernant l'activation du Tiering des données et du stockage WORM :

* Les données transférées vers le stockage objet n'incluent pas la fonctionnalité WORM d'ONTAP. Pour garantir la fonctionnalité WORM de bout en bout, vous devez configurer correctement les autorisations des compartiments.
* Les données placées dans le Tier de stockage objet n'ont pas la fonctionnalité WORM. Techniquement, quiconque dispose d'un accès complet aux compartiments et aux conteneurs peut utiliser et supprimer les objets placés à un Tier par ONTAP.
* La restauration ou la restauration à partir de Cloud Volumes ONTAP 9.8 est bloquée après l'activation de WORM et de la hiérarchisation.




== Limites

* Le stockage WORM dans Cloud Volumes ONTAP fonctionne selon un modèle « administrateur de stockage de confiance ». Les fichiers WORM sont protégés contre les modifications ou modifications, mais un administrateur du cluster peut supprimer des volumes, même si ces volumes contiennent des données WORM non expirées.
* En plus du modèle d'administrateur de stockage de confiance, le stockage WORM dans Cloud Volumes ONTAP fonctionne aussi implicitement sous un modèle d'administrateur cloud reconnu. Un administrateur cloud peut supprimer des données WORM avant leur date d'expiration en supprimant ou en modifiant directement le stockage cloud du fournisseur cloud.

