---
sidebar: sidebar 
permalink: concept-degraded-ha-pair.html 
keywords: storage takeover, storage giveback, degraded, degraded status, degraded state, ha pair, ha takeover, takeover, giveback 
summary: 'Lorsqu"un nœud d"une paire HA n"est pas disponible, l"autre nœud transmet les données à son partenaire pour assurer la continuité du service de données. Il s"agit de l"appel d"acquisition du stockage. Plusieurs actions sont indisponibles jusqu"à la fin du rétablissement dans le stockage.' 
---
= Actions non disponibles lors du basculement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsqu'un nœud d'une paire HA n'est pas disponible, l'autre nœud transmet les données à son partenaire pour assurer la continuité du service de données. Il s'agit de la_prise de contrôle_ du stockage. Plusieurs actions sont indisponibles jusqu'à la fin du rétablissement dans le stockage.


TIP: Lorsqu'un nœud d'une paire HA n'est pas disponible, l'état de l'environnement de travail dans BlueXP est _dégradé_.

Les actions suivantes ne sont pas disponibles depuis BlueXP Storage Takeover :

* Inscription au support
* Modifications de licence
* Modifications du type d'instance ou de VM
* Modification de la vitesse d'écriture
* Configuration CIFS
* Modification de l'emplacement des sauvegardes de configuration
* Définition du mot de passe du cluster
* Gestion des disques et des agrégats (allocation avancée)


Ces actions sont à nouveau disponibles une fois le rétablissement du stockage terminé et l'état de l'environnement de travail revenir à la normale.
