---
sidebar: sidebar 
permalink: concept-performance.html 
keywords: performance, technical report, TR, workload, cpu 
summary: Vous pouvez consulter les résultats des performances pour déterminer les charges de travail appropriées à Cloud Volumes ONTAP. 
---
= Performance
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez consulter les résultats des performances pour déterminer les charges de travail appropriées à Cloud Volumes ONTAP.



== Rapports techniques sur les performances

ifdef::aws[]

* Cloud Volumes ONTAP pour AWS
+
link:https://www.netapp.com/pdf.html?item=/media/9088-tr4383pdf.pdf["Rapport technique NetApp 4383 : caractérisation des performances de Cloud Volumes ONTAP dans Amazon Web Services avec des charges de travail applicatives"^]



endif::aws[]

ifdef::azure[]

* Cloud Volumes ONTAP pour Microsoft Azure
+
link:https://www.netapp.com/pdf.html?item=/media/9089-tr-4671pdf.pdf["Rapport technique NetApp 4671 : caractérisation des performances de Cloud Volumes ONTAP dans Azure avec les charges de travail applicatives"^]



endif::azure[]

ifdef::gcp[]

* Cloud Volumes ONTAP pour Google Cloud
+
link:https://www.netapp.com/pdf.html?item=/media/9090-tr4816pdf.pdf["Rapport technique NetApp 4816 : caractérisation des performances d'Cloud Volumes ONTAP pour Google Cloud"^]



endif::gcp[]



== Performances du processeur

Les nœuds Cloud Volumes ONTAP sont pleinement exploités (plus de 90 %) à partir des outils de contrôle de votre fournisseur cloud. En effet, ONTAP se réserve tous les CPU virtuels présentés à la machine virtuelle afin qu'ils soient disponibles en cas de besoin.

Pour obtenir de l'aide, reportez-vous au https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Monitoring_CPU_utilization_before_an_ONTAP_upgrade["Article de la base de connaissances NetApp sur la façon de surveiller l'utilisation du CPU ONTAP à l'aide de l'interface de ligne de commande"^]
