---
sidebar: sidebar 
permalink: concept-client-protocols.html 
keywords: client protocols, client version, smb version, nfs version, protocol versions, s3, smb, nfs, iscsi, cifs 
summary: Cloud Volumes ONTAP prend en charge les protocoles client iSCSI, NFS, SMB, NVMe-TCP et S3. 
---
= Protocoles clients
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP prend en charge les protocoles client iSCSI, NFS, SMB, NVMe-TCP et S3.



== ISCSI

ISCSI est un protocole de bloc capable de s'exécuter sur les réseaux Ethernet standard. La plupart des systèmes d'exploitation clients proposent un initiateur logiciel qui fonctionne sur un port Ethernet standard.



== NFS

NFS est le protocole d'accès classique aux fichiers pour les systèmes UNIX et LINUX. Les clients peuvent accéder aux fichiers des volumes ONTAP à l'aide des protocoles NFS v3, NFS V4 et NFS v4.1. Vous pouvez contrôler l'accès aux fichiers à l'aide d'autorisations de style UNIX, d'autorisations de style NTFS ou d'une combinaison des deux.

Les clients peuvent accéder aux mêmes fichiers à l'aide des protocoles NFS et SMB.



== PME

SMB est le protocole d'accès aux fichiers traditionnel pour les systèmes Windows. Les clients peuvent accéder aux fichiers des volumes ONTAP à l'aide des protocoles SMB 2.0, SMB 2.1, SMB 3.0 et SMB 3.1.1. Tout comme avec NFS, plusieurs styles d'autorisation sont pris en charge.



== S3

Cloud Volumes ONTAP prend en charge S3 en option pour le stockage scale-out. La prise en charge du protocole S3 permet de configurer l'accès des clients S3 aux objets contenus dans un compartiment d'une machine virtuelle de stockage (SVM).

link:https://docs.netapp.com/us-en/ontap/s3-multiprotocol/index.html#how-s3-multiprotocol-works["Fonctionnement multiprotocole S3"^].
link:https://docs.netapp.com/us-en/ontap/object-storage-management/index.html["Découvrez comment configurer et gérer les services de stockage objet S3 dans ONTAP"^].



== NVMe-TCP

Le protocole NVMe-TCP est pris en charge par les fournisseurs cloud si vous utilisez Cloud Volumes ONTAP version 9.12.1 ou ultérieure. BlueXP ne propose pas de fonctionnalités de gestion pour NVMe-TCP.

Pour plus d'informations sur la configuration de NVMe via ONTAP, reportez-vous à la section https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-nvme-task.html["Configuration d'une VM de stockage pour NVMe"^].
