---
sidebar: sidebar 
permalink: faq-config-support.html 
keywords: FAQ, Frequently asked questions, questions, configuration, 
summary:  
---
= Configuration et périphériques pris en charge
:allow-uri-read: 


[role="lead"]
Cette FAQ répond aux questions les plus courantes sur la configuration de Cloud Insights et les périphériques pris en charge.



== Cloud Insights modifie-t-il mon environnement ?

Non Cloud Insights est un outil en lecture seule qui recueille des informations sur votre environnement. Cloud Insights ne modifie jamais vos ressources ni vos configurations.



== Quel accès de niveau d'autorisation Cloud Insights a-t-il besoin pour mes appareils ?

Dans la plupart des cas où le périphérique le prend en charge, un accès en lecture seule est tout ce qui est nécessaire. Certaines solutions n'autorisent pas l'accès en lecture seule et requièrent donc les autorisations élevées appropriées.



== Quelle est la fréquence de collecte des informations par Cloud Insights ?

Cloud Insights collecte généralement les données de performance toutes les 5 minutes et la découverte de constructions logiques et physiques toutes les ½ heures Cloud Insights définit les intervalles d'interrogation par défaut en fonction des meilleures pratiques suggérées et de l'évolutivité, mais elle permet à l'utilisateur de contrôler ces intervalles de façon complète.



== Quel est l'impact de Cloud Insights sur mon environnement ?

Les communications IP passives et hors bande sans agent de Cloud Insights réduisent la configuration, la maintenance et l'impact sur l'écosystème du data Center. L'équipe de développement des performances de Cloud Insights prend de très bons mesures pour minimiser l'impact sur les performances du data Center dans le cadre d'activités de surveillance des performances lui-même. L'impact est considéré comme négligeable dans les environnements d'exploitation normaux et peut être détendu ou resserré dans des plateformes technologiques hautement utilisées ou sous-performantes. Consultez le Guide d'installation de Cloud Insights pour plus d'informations.



== Comment puis-je répertorier tous les hôtes/machines virtuelles dans Cloud Insights ?

Le compliment de widgets et de possibilités de liste de requêtes de Cloud Insights peut être utilisé pour fournir des listes de styles d'inventaire pour les ressources de Data Center. Les listes des machines virtuelles jusqu'aux piles de disques et de nombreuses constructions entre elles peuvent toutes être mises à disposition pour les requêtes, les widgets, les tableaux de bord et les rapports d'entrepôts de données, et sont accessibles via l'API RESTful.



== Cloud Insights fournit-il le même type de prise en charge pour les hôtes non hyperviseurs associés (par exemple, les serveurs physiques) ?

Les hyperviseurs tels que VMware fournissent des informations détaillées sur les hôtes ESXI et leurs machines virtuelles (VM). Pour les serveurs physiques, Cloud Insights collecte des mesures jusqu'à la carte HBA hôte. Cloud Insights utilise une méthode unique pour découvrir des serveurs physiques à l'aide d'une technologie de brevet en attente. Une fois le stockage et/ou les commutateurs découverts, les noms d'hôtes des serveurs physiques figurent dans les informations d'alias de structure. Cloud Insights sélectionne ces noms d'hôte, les met en correspondance dans le DNS et place automatiquement les hôtes dans Cloud Insights. Cette technique réduit considérablement le besoin de mises à jour manuelles des entrées et de maintenance de l'inventaire des outils.



== Cloud Insights fournit-il la même profondeur de mesure de périphérique (parité) pour les environnements hétérogènes ?

Il existe différents degrés de standardisation, de similarité et de nomenclature au sein des plateformes et des technologies des fournisseurs tiers. Cloud Insights essaie de normaliser les informations relatives à la capacité et aux performances pour un cadre cohérent. Certaines mesures de capacité et de performance sont fournies de manière native depuis les compteurs de l'appareil, tels que les IOPS, la latence et la capacité brute. Lorsque des compteurs ne sont pas fournis, Cloud Insights peut tenter de résumer les valeurs (par exemple, en totalisant les IOPS ou les capacités des volumes sous-jacents). Dans le cas où aucun de ces compteurs n'est disponible, Cloud Insights tentera de déduire les valeurs des mesures à l'aide de différents algorithmes de calcul. Cloud Insights offre une fonctionnalité d'intégration SNMP générique pour intégrer d'autres mesures non actuellement collectées par Cloud Insights.



== L'Cloud Insights prend-il en charge les commutateurs Fibre Channel ?

Oui, en plus de collecter les données provenant de vos actifs de stockage, Cloud Insights acquiert également des données d'inventaire et de performances de commutateurs Cisco, Brocade et QLogic dans votre environnement.

==les vues topologiques de l'ensemble de l'infrastructure sont-elles disponibles ? Cloud Insights affiche-t-il une « visibilité de bout en bout » ?

Oui, Cloud Insights détecte et mappe de façon dynamique les constructions logiques et physiques, et fournit une vue interactive de la topologie de bout en bout des ressources de calcul, de fabrics, de virtualiseurs et de stockage interne. Les icônes de topologie permettent de parcourir rapidement les ressources affectées et d'identifier les charges de travail et les violations dans les environnements de stockage partagé.
