---
sidebar: sidebar 
permalink: io_density_nonroot.html 
keywords: notifications, annotations, queries, applications, 
summary: Densité des E/S. 
---
= Les données de densité d'E/S ne décrivent que les volumes de données internes
:allow-uri-read: 


[role="lead"]
Sur les systèmes de stockage NetApp, l'agrégat racine contient le volume racine contenant des répertoires spéciaux et des fichiers de configuration pour gérer et contrôler le système de stockage. Ces opérations peuvent entraîner une activité importante dans l'agrégat racine. Lorsque vous effectuez une requête sur Cloud Insights pour les 10 principaux volumes internes dont la densité d'E/S est la plus élevée, les résultats peuvent inclure des agrégats racine NetApp dans les 10 principaux résultats.

Lors de la surveillance de votre environnement, il est plus important de déterminer quels volumes de données internes produisent des chiffres de densité d'E/S élevés. Pour identifier avec précision uniquement les volumes de données, vous devez isoler les volumes internes NetApp des requêtes utilisées pour surveiller la densité des E/S.

Ce guide explique comment identifier facilement les agrégats racine NetApp, les isoler des résultats des requêtes de volume internes et créer des règles qui excluent tous les nouveaux agrégats racine NetApp lors de leur ajout au système. Les fonctionnalités Cloud Insights suivantes sont utilisées pour vérifier que vos rapports de densité d'E/S sont issus des volumes de données internes.

* Une requête est créée afin d'identifier tous les agrégats racine NetApp surveillés par Cloud Insights.
* Une annotation est attribuée à chacun des agrégats racines NetApp.
* Une règle d'annotation est créée afin d'exclure les agrégats racines NetApp.




== Création d'une requête permettant d'identifier les agrégats racine NetApp dans votre environnement

Les requêtes fournissent une recherche granulaire, en fonction des critères sélectionnés par l'utilisateur. Une requête vous permet de rechercher des volumes internes dans votre environnement contenant l'agrégat racine NetApp.

.Étapes
. Dans Cloud Insights, créez une requête pour identifier les agrégats racines NetApp dans votre environnement : *requêtes > +Nouvelle requête > Storage Pool*
. Entrer le nom de l'agrégat root
+
Cet exemple utilise "aggr0" pour le nom. Lors de la création d'un agrégat, seules les exigences suivantes concernant le nom doivent être respectées :

+
** Il doit commencer par une lettre ou un trait de soulignement (_).
** Il ne peut contenir que des lettres, des chiffres et des traits de soulignement.
** Elle peut comporter 250 caractères maximum.




Dans la plupart des cas, l'agrégat est nommé aggr0, aggr_0, ou quelque chose de similaire. Cela peut impliquer un processus itératif pour identifier tous les agrégats racines NetApp de votre environnement.

. Cliquez sur *Enregistrer* et entrez un nom pour la nouvelle requête.
+
Comme mentionné précédemment, il peut s'agir d'un processus itératif et nécessite plusieurs requêtes pour identifier tous les agrégats racines NetApp.





== Créez une annotation pour les volumes racine renvoyés par vos requêtes

Les annotations sont des notes spécialisées que vous attribuez à vos ressources, ce qui vous permet de filtrer les ressources par leurs annotations. Cette annotation vous permettra d'identifier les agrégats NetApp racine dans votre environnement et de vérifier qu'ils ne sont pas inclus dans une liste de volumes internes dont la densité d'E/S est la plus élevée.

.Avant de commencer
Vous devez avoir identifié tous les agrégats racine à exclure du rapport « densité d'E/S élevée ».

.Étapes
. Créez une annotation pour associer tous les agrégats racine NetApp identifiés à des requêtes : *Manage > Annotations*
+
.. Entrez le nom de l'annotation : *RootAggr*
.. Entrez une description de l'annotation : *Supprimer l'agrégat racine de la liste "densité d'E/S élevée"*
.. Saisissez le type d'annotation : *Boolean*


. Cliquez sur *Enregistrer*




== Créez une règle d'annotation pour automatiser l'exclusion des agrégats spécifiques de votre rapport de densité d'E/S.

Au lieu d'appliquer manuellement des annotations à des ressources individuelles, vous pouvez appliquer automatiquement des annotations à plusieurs ressources à l'aide de règles d'annotation. Les règles d'annotation sont basées sur les requêtes que vous créez et lorsqu'elles sont exécutées sur le système, elles ajoutent de nouvelles ressources à des ensembles de ressources existants. Lorsque ces ensembles d'actifs sont exclus de l'inclusion, les nouveaux actifs sont également automatiquement exclus.

.Avant de commencer
Vous devez avoir créé et enregistré une requête qui identifie les agrégats racine NetApp que vous avez identifiés dans votre environnement.

.Étapes
. Dans le menu Cloud Insights, cliquez sur *gérer > Annotations*
. Cliquez sur *Ajouter*
. Procédez comme suit :
+
.. Dans la zone Nom, entrez un nom unique qui décrit la règle : *RootAggrExclude*
.. Cliquez sur requête et sélectionnez la requête que Cloud Insights doit utiliser pour appliquer la règle d'annotation à : *Aggregate0*
.. Cliquez sur Annotation et sélectionnez : *exclusion d'agg racine*
.. Cliquez sur *valeur* et saisissez *vrai*



