---
sidebar: sidebar 
permalink: task-verify-autosupport.html 
keywords: autosupport, set up autosupport, test autosupport, asup, test asup 
summary: 'AutoSupport surveille de manière proactive l"état de santé de votre système et envoie des messages au support technique NetApp. Par défaut, AutoSupport est activé sur chaque nœud pour envoyer des messages au support technique via le protocole de transport HTTPS. Il est préférable de vérifier que AutoSupport peut envoyer ces messages.' 
---
= Vérifiez la configuration de AutoSupport
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AutoSupport surveille de manière proactive l'état de santé de votre système et envoie des messages au support technique NetApp. Par défaut, AutoSupport est activé sur chaque nœud pour envoyer des messages au support technique via le protocole de transport HTTPS. Il est préférable de vérifier que AutoSupport peut envoyer ces messages.

La seule étape de configuration requise consiste à s'assurer que Cloud Volumes ONTAP dispose d'une connexion Internet sortante. Pour plus d'informations, consultez les exigences de mise en réseau de votre fournisseur de cloud.



== Conditions requises pour le AutoSupport

Les nœuds Cloud Volumes ONTAP nécessitent un accès Internet sortant pour l'AutoSupport, qui surveille de manière proactive l'état de santé de votre système et envoie des messages au support technique de NetApp.

Les règles de routage et de pare-feu doivent autoriser le trafic HTTP/HTTPS vers les terminaux suivants pour que Cloud Volumes ONTAP puisse envoyer les messages AutoSupport :

* \https://support.netapp.com/aods/asupmessage
* \https://support.netapp.com/asupprod/post/1.0/postAsup


Si aucune connexion Internet sortante n'est disponible pour envoyer des messages AutoSupport, BlueXP configure automatiquement vos systèmes Cloud Volumes ONTAP pour utiliser le connecteur comme serveur proxy. La seule condition est de s'assurer que le groupe de sécurité du connecteur autorise les connexions _entrantes_ sur le port 3128. Vous devrez ouvrir ce port après le déploiement du connecteur.

Si vous avez défini des règles sortantes strictes pour Cloud Volumes ONTAP, vous devrez également vous assurer que le groupe de sécurité Cloud Volumes ONTAP autorise les connexions _sortantes_ sur le port 3128.

Après avoir vérifié que l'accès Internet sortant est disponible, vous pouvez tester AutoSupport pour vous assurer qu'il peut envoyer des messages. Pour obtenir des instructions, reportez-vous à la section https://docs.netapp.com/us-en/ontap/system-admin/setup-autosupport-task.html["Documentation ONTAP : configuration d'AutoSupport"^].



== Résoudre les problèmes de configuration AutoSupport

Si une connexion sortante n'est pas disponible et que BlueXP ne peut pas configurer votre système Cloud Volumes ONTAP pour utiliser le connecteur comme serveur proxy, vous recevrez une notification de BlueXP intitulée "<nom de l'environnement de travail> ne peut pas envoyer de messages AutoSupport ".

Vous recevez probablement ce message en raison de problèmes de réseau.

Procédez comme suit pour résoudre ce problème.

.Étapes
. SSH vers le système Cloud Volumes ONTAP afin que vous puissiez gérer le système à partir de l'interface de ligne de commandes.
+
link:task-connecting-to-otc.html["Découvrez comment SSH vers Cloud Volumes ONTAP"].

. Afficher l'état détaillé du sous-système AutoSupport :
+
`autosupport check show-details`

+
La réponse doit être similaire à ce qui suit :

+
[listing]
----
    Category: smtp
          Component: mail-server
             Status: failed
             Detail: SMTP connectivity check failed for destination:
                     mailhost. Error: Could not resolve host - 'mailhost'
            Corrective Action: Check the hostname of the SMTP server

    Category: http-https
        Component: http-put-destination
            Status: ok
            Detail: Successfully connected to:
                    <https://support.netapp.com/put/AsupPut/>.

          Component: http-post-destination
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/asupprod/post/1.0/postAsup.

    Category: on-demand
          Component: ondemand-server
             Status: ok
             Detail: Successfully connected to:
                     https://support.netapp.com/aods/asupmessage.

    Category: configuration
            Component: configuration
                Status: ok
                Detail: No configuration issues found.
    5 entries were displayed.
----
+
Si l'état de la catégorie http-https est « ok », cela signifie que AutoSupport est configuré correctement et que des messages peuvent être envoyés.

. Si l'état n'est pas ok, vérifiez l'URL du proxy pour chaque noeud Cloud Volumes ONTAP :
+
`autosupport show -fields proxy-url`

. Si le paramètre d'URL du proxy est vide, configurez Cloud Volumes ONTAP pour utiliser le connecteur comme proxy :
+
`autosupport modify -proxy-url \http://<connector private ip>:3128`

. Vérifiez à nouveau l'état du disque AutoSupport :
+
`autosupport check show-details`

. Si l'état est toujours échec, vérifiez qu'il y a une connectivité entre Cloud Volumes ONTAP et le connecteur sur le port 3128.
. Si l'ID d'état échoue toujours après vérification de la connectivité, SSH vers le connecteur.
+
https://docs.netapp.com/us-en/bluexp-setup-admin/task-managing-connectors.html#connect-to-the-linux-vm["En savoir plus sur la connexion à la VM Linux pour le connecteur"^]

. Accédez à `/opt/application/netapp/cloudmanager/docker_occm/data/`
. Ouvrez le fichier de configuration du proxy `squid.conf`
+
La structure de base du fichier est la suivante :

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
+
La valeur localnet src est le CIDR du système Cloud Volumes ONTAP.

. Si le bloc CIDR du système Cloud Volumes ONTAP n'est pas dans la plage spécifiée dans le fichier, mettez à jour la valeur ou ajoutez une nouvelle entrée comme suit :
+
`acl cvonet src <cidr>`

+
Si vous ajoutez cette nouvelle entrée, n'oubliez pas d'ajouter également une entrée Autoriser :

+
`http_access allow cvonet`

+
Voici un exemple :

+
[listing]
----
        http_port 3128
        acl localnet src 172.31.0.0/16
        acl cvonet src 172.33.0.0/16
        acl azure_aws_metadata dst 169.254.169.254

        http_access allow localnet
        http_access allow cvonet
        http_access deny azure_aws_metadata
        http_access allow localhost
        http_access deny all
----
. Après avoir modifié le fichier de configuration, redémarrez le conteneur proxy comme suit :
+
`docker restart squid`

. Retournez à l'interface de ligne de commandes de Cloud Volumes ONTAP et vérifiez que Cloud Volumes ONTAP peut envoyer des messages AutoSupport :
+
`autosupport check show-details`


