---
sidebar: sidebar 
permalink: task_dc_nutanix.html 
keywords: data collector, Nutanix, NX Series 
summary: Configuration du collecteur de données Nutanix. 
---
= Collecteur de données Nutanix NX
:allow-uri-read: 


[role="lead"]
Cloud Insights utilise le collecteur de données Nutanix pour découvrir les données d'inventaire et de performance des systèmes de stockage Nutanix NX.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données de Nutanix. Pour chaque type de bien acquis par Cloud Insights, la terminologie la plus utilisée pour ce bien est présentée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Pool de stockage | Pool de stockage 


| Conteneur Nutanix | Volume interne 


| Conteneur Nutanix | Partage de fichiers 


| Partage NFS | Partagez 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* L'adresse IP des services de données externes pour le cluster
* Nom d'utilisateur et mot de passe en lecture seule, sauf si des groupes_volumes sont utilisés, auquel cas, le nom d'utilisateur et le mot de passe administrateur sont requis
* Port requis : HTTPS 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP externe prismes | L'adresse IP des services de données externes pour le cluster 


| Nom d'utilisateur | Nom d'utilisateur du compte Admin 


| Mot de passe | Mot de passe du compte admin 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour la connexion à la baie Nutanix. La valeur par défaut est 9440. 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 60 minutes. 


| Intervalle(s) d'interrogation de performance | Intervalle entre les sondages de performances. La valeur par défaut est 300 secondes. 
|===


== Dépannage

Pour plus d'informations sur ce Data Collector, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
