---
sidebar: sidebar 
permalink: task_dc_hpe_nimble.html 
keywords: data collector, HP Nimble, HP, HPE, Alletra 6000 
summary: 'Configuration du collecteur de données HP Enterprise Alletra 6000 (anciennement Nimble).' 
---
= Collection de données HPE Alletra 6000
:allow-uri-read: 


[role="lead"]
Le collecteur de données HP Enterprise Alletra 6000 (anciennement Nimble) prend en charge les données d'inventaire et de performance des baies de stockage Alletra 6000.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes auprès de ce collecteur. Pour chaque type de bien acquis par Cloud Insights, la terminologie la plus utilisée pour ce bien est présentée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Baie | Stockage 


| Disque | Disque 


| Volumétrie | Volumétrie 


| Piscine | Pool de stockage 


| Initiateur | Alias de l'hôte de stockage 


| Contrôleur | Nœud de stockage 


| Interface Fibre Channel | Contrôleur 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

Vous devez disposer des éléments suivants pour collecter les données d'inventaire et de configuration de la baie de stockage :

* La baie doit être installée et configurée, et accessible depuis le client via son nom de domaine complet (FQDN) ou son adresse IP de gestion de baie.
* La baie doit exécuter NimbleOS 2.3.x ou une version ultérieure.
* Vous devez disposer d'un nom d'utilisateur et d'un mot de passe valides pour la baie ayant au moins le rôle « opérateur ». Le rôle « invité » ne dispose pas d'un accès suffisant pour comprendre les configurations des initiateurs.
* Le port 5392 doit être ouvert sur la matrice.


Pour collecter les données de performances de la baie de stockage, vous devez disposer des éléments suivants :

* La baie doit exécuter NimbleOS 4.0.0 ou une version ultérieure
* Les volumes de la matrice doivent être configurés. La seule API de performance NimbleOS concerne les volumes et tous les rapports de statistiques Cloud Insights sont issus des statistiques sur les volumes




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de gestion de baie | Nom de domaine complet (FQDN) ou adresse IP de gestion de baie. 


| Nom d'utilisateur | Nom d'utilisateur de la matrice 


| Mot de passe | Mot de passe de la matrice 
|===


== Configuration avancée

|===


| Champ | Description 


| Port | Port utilisé par l'API REST Nimble. La valeur par défaut est 5392. 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 60 minutes. 
|===
Remarque : l'intervalle d'interrogation par défaut est de 300 secondes et ne peut pas être modifié. Il s'agit du seul intervalle pris en charge par HPE Alletra 6000.
