---
sidebar: sidebar 
permalink: task_device_resolution_preferences.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution, FC, Identify 
summary:  
---
= Configuration des options dans l'onglet Préférences
:allow-uri-read: 


[role="lead"]
L'onglet Préférences de résolution du périphérique permet de créer un programme de résolution automatique, de spécifier des venders de stockage et de bande à inclure ou exclure de l'identification, et de définir des options de recherche DNS.



=== Planning de résolution automatique

Un planning de résolution automatique peut indiquer quand la résolution automatique du périphérique est exécutée :

|===


| Option | Description 


| Toutes les | Utilisez cette option pour exécuter la résolution automatique des périphériques aux intervalles de jours, heures ou minutes. 


| Tous les jours | Utilisez cette option pour exécuter la résolution automatique du périphérique tous les jours à une heure donnée. 


| Manuellement | Utilisez cette option pour exécuter uniquement la résolution automatique des périphériques manuellement. 


| Sur chaque changement d'environnement | Utilisez cette option pour exécuter la résolution automatique des périphériques lorsqu'un changement d'environnement est apporté. 
|===
Si vous spécifiez _manuellement_, la résolution automatique nocturne du périphérique est désactivée.



=== Options de traitement DNS

Les options de traitement DNS vous permettent de sélectionner les fonctions suivantes :

* Lorsque le traitement des résultats de recherche DNS est activé, vous pouvez ajouter une liste de noms DNS à ajouter aux périphériques résolus.
* Vous pouvez sélectionner résolution automatique des adresses IP : pour activer la résolution automatique des hôtes pour les initiateurs et les hôtes iSCSI qui accèdent aux partages NFS à l'aide de la recherche DNS. Si ce n'est pas spécifié, seule la résolution FC est effectuée.
* Vous pouvez choisir d'autoriser des traits de soulignement dans les noms d'hôte et d'utiliser un alias « connecté à » au lieu de l'alias de port standard dans les résultats.




=== Y compris les fournisseurs spécifiques de systèmes de stockage et de bandes, ou l'exclusion de ces fournisseurs

Vous pouvez inclure ou exclure certains fournisseurs de stockage et de bandes pour la résolution automatique. Vous pouvez exclure des fournisseurs spécifiques si vous savez, par exemple, qu'un hôte spécifique deviendra un hôte hérité et qu'il doit être exclu de votre nouvel environnement. Vous pouvez également réajouter des fournisseurs que vous avez précédemment exclus mais qui ne souhaitez plus exclure.


NOTE: Les règles de résolution des périphériques pour bande ne fonctionnent que pour les WWN où le fournisseur pour ce WWN est défini sur _inclus comme bande uniquement_ dans les préférences des fournisseurs.

Voir aussi : link:concept_device_resolution_regex_examples.html["Exemples d'expression régulière"]
