---
sidebar: sidebar 
permalink: task_dc_na_astra_data_store.html 
summary: Configurez le magasin de données NetApp Astra 
keywords: data collector, queries, create, astra, data, store, 
---
= Collecteur de données NetApp Astra Data Store
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert les données d'inventaire et de performance pour un seul cluster de magasin de données Astra. Outre le collecteur de données, l'opérateur de surveillance configure _Telegraf_ pour collecter des mesures avancées et _fluent bit_ pour collecter des journaux.


TIP: Vous trouverez également ces instructions d'installation et d'autres informations dans la documentation du magasin de données Astra :link:https://docs.netapp.com/us-en/astra-data-store/use/monitor-with-cloud-insights.html["Surveillance des metrics grâce à Cloud Insights"]
link:https://docs.netapp.com/us-en/astra-data-store/get-started/quick-start.html["Découvrez Astra Data Store"]



== Terminologie

Cloud Insights acquiert les données d'inventaire et de performance à partir de ce collecteur de données. Pour chaque type d'actif acquis, la terminologie la plus utilisée pour l'actif est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| AstrakDSVolume | Volume interne 


| AstradDSNodeInfo.status.disques | Disque 


| AstradDSNodeInfo | Nœud de stockage 


| Règles AstrasDSExportPolicy | Initiateur partage/partage 


| AstrakDSCluster | Stockage 
|===


== De formation

* L'opérateur de surveillance NetApp doit être installé dans le cluster Kubernetes avec le magasin de données Astra. Si ce n'est pas le cas lors de l'installation du magasin de données Astra, installez l'opérateur de surveillance conformément aux instructions d'installation du magasin de données Astra.
* Le plugin _kubectl-astrads_ kubectl doit être installé. Si elle n'est pas installée, installez le fichier binaire _kubectl-astrads_ en suivant les instructions d'installation de l'Astra Data Store.
* Les commandes suivantes doivent être disponibles : _awk, curl, grep et jq_.




== Installation

Le script d'installation vous fera découvrir l'installation du collecteur de données Astra Data Store. Suivez les instructions à l'écran. L'installation prend plusieurs minutes. Une fois cette opération terminée, l'affichage des données dans Cloud Insights peut prendre quelques minutes supplémentaires.

Le script vous présente les étapes suivantes :

. Choisissez un token d'accès API.
. Copiez le script du programme d'installation à partir de la boîte de dialogue d'installation et enregistrez-le sous la forme d'un fichier nommé _cloudInsights-ADS-monitoring.sh_. Vous pouvez cliquer sur l'icône du presse-papiers pour copier rapidement le script dans le presse-papiers.
. Ouvrez une fenêtre Bash, changez le répertoire à l'emplacement du script _cloudInsights-ADS-monitoring.sh_.
. Copiez le bloc de commande des autorisations à partir de la boîte de dialogue d'installation. Vous pouvez cliquer sur l'icône du presse-papiers pour copier rapidement la commande dans le presse-papiers.
. Collez la commande permissions dans la fenêtre Bash et appuyez sur entrée.
. Copiez la commande d'installation à partir de la boîte de dialogue d'installation. Vous pouvez cliquer sur l'icône du presse-papiers pour copier rapidement la commande dans le presse-papiers.
. Collez la commande d'installation dans la fenêtre Bash.
. Remplacez <KUBERNETES_IP> par l'adresse IP du serveur API Kubernetes.
. Remplacez <KUBERNETES_TOKEN> par votre jeton d'API Kubernetes.
. Appuyez sur entrée.
+
Le script d'installation : * Vérifiez que l'opérateur de surveillance est installé et configuré. * Configurer le bit Fluent. * Configurer Telegraf. * Installer l'unité d'acquisition. * Installez le collecteur de magasin de données Astra une fois que l'unité d'acquisition est en cours d'exécution.

. Cliquez sur _Complete Setup_.


Si le script d'installation se ferme en raison d'une erreur, vous pouvez le relancer une fois l'erreur résolue. Le script d'installation prend en charge des paramètres supplémentaires tels que l'espace de noms de l'opérateur de surveillance et le port du serveur d'API Kubernetes si votre environnement n'utilise pas les paramètres par défaut. Vous trouverez ci-dessous la liste complète des options disponibles.



=== Options du script du programme d'installation :

Notez que le nom de domaine Cloud Insights et la clé d'accès à l'API sélectionnée seront intégrés dans le script d'installation lors du téléchargement.

....
$ ./cloudinsights-ads-monitoring.sh -h
USAGE: cloudinsights-ads-monitoring.sh [OPTIONS]
Configure monitoring of Astra Data Store by Cloud Insights.
OPTIONS:
 -h                      Display this help message.
 -d ci_domain_name       Cloud Insights tenant domain name.
 -i kubernetes_ip        Kubernetes API server IP address.
 -k ci_api_key           Cloud Insights API Access Key.
 -n namespace            Namespace for monitoring components. (default: netapp-monitoring)
 -p kubernetes_port      Kubernetes API server port. (default: 6443)
 -r root_pv_dir          Create 3 Persistent Volumes in this directory for the Acquisition Unit.
                         Only specify this option if there is no Storage Provisioner installed and the PVs do not already exist.
 -s storage_class        Storage Class name for provisioning Acquisition Unit PVs. If not specified, the default storage class will be used.
 -t kubernetes_token     Kubernetes API server token.
....


== Dépannage

Certaines choses à essayer si vous rencontrez des problèmes avec ce collecteur de données :



==== Collecteur de données de magasin de données Astra

[cols="2*"]
|===
| Problème : | Essayer : 


| Un message « non autorisé » s'affiche | Vérifiez que le token d'API Kubernetes est autorisé à appeler des API dans l'iGroup _astrads.netapp.io_ 


| "Hôte inconnu: Astrads-metrics-service.astrads-system.svc.cluster.local: Nom ou service inconnu" | Vérifiez que le collecteur est installé dans un pod d'unité d'acquisition qui s'exécute à l'intérieur du cluster ADS Kubernetes. Vérifiez que le service astrads-metrics exécute l'espace de noms du système astrads. 
|===


==== Script d'installation

[cols="2*"]
|===
| Problème : | Essayer : 


| L'opérateur de surveillance n'est pas en cours d'exécution dans <namespace>. | Suivez les instructions d'installation de l'Astra Data Store pour l'installer 


| Le module d'unité d'acquisition <pod> ne s'est pas démarré correctement après 300 secondes. | Obtenir le nom du pod d'unité d'acquisition : kubectl get pods --namespace netapp-monitoring | grep « au-pod » Vérifiez les événements du pod pour des erreurs : kubectl décris pod --namespace netapp-monitoring <POD_NAME> 


| L'installation de l'unité d'acquisition n'est pas terminée au bout de 900 secondes | Obtenir le nom du pod d'unité d'acquisition : kubectl get pods --namespace netapp-monitoring | grep « au-pod » Vérifiez les journaux d'erreurs : kubectl logs -- Namespace NetApp-monitoring <POD_NAME> si aucune erreur ne se produit et que les journaux se terminent par le message « main - l'acquisition est active et fonctionne ! », l'installation est réussie, mais trop longue que prévu. Exécutez à nouveau le script d'installation. 


| Impossible de récupérer l'ID d'unité d'acquisition à partir de Cloud Insights | Vérifiez que l'unité d'acquisition apparaît dans Cloud Insights. Accédez à Admin > Data Collectors et cliquez sur l'onglet unités d'acquisition. Vérifiez que la clé API Cloud Insights est autorisée pour l'unité d'acquisition. 
|===
Pour plus d'informations sur ce Data Collector, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
