---
sidebar: sidebar 
permalink: task_view_configured_data_collectors.html 
keywords: acquisition, AU, data collector, collector, bulk edit, postpone polling, resume polling 
summary: Un résumé. 
---
= Gestion des collecteurs de données configurés
:allow-uri-read: 


[role="lead"]
La page collecteurs de données installés permet d'accéder aux collecteurs de données configurés pour Cloud Insights. Vous pouvez utiliser cette page pour modifier des collecteurs de données existants.

.Étapes
. Dans le menu Cloud Insights, cliquez sur *Admin > Data Collectors*
+
L'écran collecteurs de données disponibles s'affiche.

. Cliquez sur *collecteurs de données installés*
+
Une liste de tous les collecteurs de données installés s'affiche. La liste fournit le nom du collecteur, son état, l'adresse IP à laquelle le collecteur accède et quand les données ont été acquises pour la dernière fois depuis le périphérique A. Les actions pouvant être effectuées sur cet écran sont les suivantes :

+
** Contrôle de l'interrogation
** Modifier les informations d'identification du collecteur de données
** Collecteurs de données de clonage






== Contrôle de l'interrogation du Data Collector

Après avoir apporté une modification à un collecteur de données, vous pouvez interroger immédiatement pour vérifier vos modifications ou reporter la collecte de données sur un collecteur de données pendant un, trois ou cinq jours pendant que vous travaillez sur un problème.

.Étapes
. Dans le menu Cloud Insights, cliquez sur *Admin > Data Collectors*
. Cliquez sur *collecteurs de données installés*
. Cochez la case à gauche du Data Collector que vous souhaitez modifier
. Cliquez sur *actions groupées* et sélectionnez l'action d'interrogation que vous souhaitez effectuer.
+
Les actions en bloc peuvent être exécutées simultanément sur plusieurs collecteurs de données. Sélectionnez les collecteurs de données et choisissez l'action à effectuer dans le menu *action groupée*.





== Modification des informations du collecteur de données

Vous pouvez modifier les informations de configuration existantes du collecteur de données.

.Pour modifier un collecteur de données unique :
. Dans le menu Cloud Insights, cliquez sur *Admin > Data Collectors* pour ouvrir la liste des collecteurs de données installés.
. Dans le menu d'options à droite du collecteur de données que vous souhaitez modifier, cliquez sur *Modifier*.
+
La boîte de dialogue Modifier le collecteur s'ouvre.

. Entrez les modifications et cliquez sur *Tester la configuration* pour tester la nouvelle configuration ou cliquez sur *Enregistrer* pour enregistrer la configuration.


Vous pouvez également modifier plusieurs collecteurs de données :

. Cochez la case à gauche de chaque collecteur de données que vous souhaitez modifier.
. Cliquez sur le bouton *actions groupées* et choisissez *Modifier* pour ouvrir la boîte de dialogue Modifier le collecteur de données.
. Modifiez les champs comme ci-dessus.
+

NOTE: Les collecteurs de données sélectionnés doivent être du même fournisseur et du même modèle et résident sur la même unité d'acquisition.

+
Lors de l'édition de plusieurs collecteurs de données, le champ Nom du collecteur de données affiche "Mixte" et ne peut pas être modifié. D'autres champs, tels que le nom d'utilisateur et le mot de passe, affichent « Mixte » et peuvent être modifiés. Les champs qui partagent la même valeur sur les collecteurs de données sélectionnés affichent les valeurs actuelles et peuvent être modifiés.

+
Lors de l'édition de plusieurs collecteurs de données, le bouton *Test Configuration* n'est pas disponible.





== Clonage des collecteurs de données

La fonction de clonage permet d'ajouter rapidement une source de données dotée des mêmes identifiants et attributs qu'une autre source de données. Le clonage vous permet de configurer facilement plusieurs instances d'un même type de périphérique.

.Étapes
. Dans le menu Cloud Insights, cliquez sur *Admin > Data Collectors*.
. Cliquez sur *collecteurs de données installés*.
. Cochez la case à gauche du collecteur de données que vous souhaitez copier.
. Dans le menu d'options à droite du collecteur de données sélectionné, cliquez sur *Clone*.
+
La boîte de dialogue Cloner le Data Collector s'affiche.

. Entrez de nouvelles informations dans les champs obligatoires.
. Cliquez sur *Enregistrer*.


.Une fois que vous avez terminé
L'opération de clonage copie tous les autres attributs et paramètres pour créer le nouveau collecteur de données.



== Exécution d'actions en bloc sur des collecteurs de données

Vous pouvez modifier simultanément certaines informations pour plusieurs collecteurs de données. Cette fonction vous permet de lancer un sondage, de reporter l'interrogation et de reprendre l'interrogation sur plusieurs collecteurs de données. En outre, vous pouvez supprimer plusieurs collecteurs de données.

.Étapes
. Dans le menu Cloud Insights, cliquez sur *Admin > Data Collectors*
. Cliquez sur *collecteurs de données installés*
. Cochez la case à gauche des collecteurs de données que vous souhaitez modifier.
. Dans le menu d'options à droite, cliquez sur l'option que vous souhaitez exécuter.


.Une fois que vous avez terminé
L'opération que vous avez sélectionnée est exécutée sur les collecteurs de données. Lorsque vous avez choisi de supprimer des collecteurs de données, une boîte de dialogue vous demande de vous conformer à l'action.
