---
sidebar: sidebar 
permalink: task_dc_emc_scaleio.html 
keywords: data collector, scaleIO, EMC, DELL 
summary: Configuration du collecteur de données Dell EMC ScaleIO 
---
= Collecteur de données DELL EMC ScaleIO
:allow-uri-read: 


[role="lead"]
Le collecteur de données ScaleIO collecte les informations d'inventaire du stockage ScaleIO. Pour la configuration, ce collecteur de données nécessite l'adresse de la passerelle ScaleIO ainsi qu'un nom d'utilisateur et un mot de passe administrateur.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données ScaleIO. Pour chaque type de bien acquis par Cloud Insights, la terminologie la plus utilisée pour ce bien est présentée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Cluster MDM (Meta Data Manager) | Stockage 


| SDS (serveur de données ScaleIO) | Nœud de stockage 


| Pool de stockage | Pool de stockage 


| Volumétrie | Volumétrie 


| Périphérique | Disque 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* Accès en lecture seule au compte utilisateur Admin
* Port requis : port HTTPS 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Passerelle(s) ScaleIO | Adresses IP ou FQDN des passerelles ScaleIO, séparées par une virgule (,) ou un point-virgule (;) 


| Nom d'utilisateur | Nom d'utilisateur Admin utilisé pour se connecter au périphérique ScaleIO 


| Mot de passe | Mot de passe utilisé pour se connecter au périphérique ScaleIO 
|===


== Configuration avancée

Cochez la case Inventaire pour activer la collecte de stock.

[cols="2*"]
|===
| Champ | Description 


| Port HTTPS | 443 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 60. 


| Délai de connexion (s) | La valeur par défaut est 60. 
|===


== Dépannage

Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
