---
sidebar: sidebar 
permalink: task_dc_emc_powerstore.html 
keywords: data collector, PowerStore, EMC, DELL 
summary: Configuration DU collecteur de données DELL EMC PowerStore. 
---
= Collecteur de données Dell EMC PowerStore
:allow-uri-read: 


[role="lead"]
Le collecteur de données EMC PowerStore rassemble les informations d'inventaire à partir du stockage EMC PowerStore. Pour la configuration, le collecteur de données nécessite l'adresse IP des processeurs de stockage ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.

Le collecteur de données EMC PowerStore rassemble les relations de réplication volume-volume que PowerStore coordonne entre les autres matrices de stockage. Cloud Insights affiche une matrice de stockage pour chaque cluster PowerStore et collecte les données d'inventaire pour les nœuds et les ports de stockage de ce cluster. Aucune donnée de volume ou de pool de stockage n'est collectée.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes à partir de ce collecteur de données. Pour chaque type de bien acquis par Cloud Insights, la terminologie la plus utilisée pour ce bien est présentée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| hôte | hôte 


| host_volume_mapping | host_volume_mapping 


| Matériel (il a des disques sous objet "extra_details"): Lecteurs | Disque 


| Appliance | Poolde stockage 


| Cluster | Baie de stockage 


| Nœud | StorageNode 


| port fc | Port 


| volumétrie | Volumétrie 


| Volume interne | système_fichiers 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

Les informations suivantes sont requises pour configurer ce collecteur de données :

* Adresse IP ou nom de domaine complet du processeur de stockage
* Nom d'utilisateur et mot de passe en lecture seule




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Passerelle(s) PowerStore | Adresses IP ou noms de domaine complets du stockage PowerStore 


| Nom d'utilisateur | Nom d'utilisateur pour PowerStore 


| Mot de passe | Mot de passe utilisé pour PowerStore 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port HTTPS | La valeur par défaut est 443 


| Intervalle d'interrogation des stocks (minutes) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 60 minutes. 
|===
La collecte des performances PowerStore de Cloud Insight utilise les données sources de granularité de 5 minutes de PowerStore. Ainsi, Cloud Insights interroge ces données toutes les cinq minutes, et ce n'est pas configurable.



== Dépannage

Pour plus d'informations sur ce Data Collector, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
