---
sidebar: sidebar 
permalink: task_dc_hds_hcp.html 
keywords: data collector, Hitachi HDS, HCP 
summary: Configuration du collecteur de données HDS. 
---
= Collecteur de données Hitachi HCP
:allow-uri-read: 


[role="lead"]
Ce collecteur de données prend en charge la plate-forme de contenu Hitachi (HCP) à l'aide de l'API de gestion HCP.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données Hitachi HCP. Pour chaque type de bien acquis par Cloud Insights, la terminologie la plus utilisée pour ce bien est présentée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Groupe HCP | Stockage 


| Locataire | Pool de stockage 


|  | Espace de noms 


| Volume interne | Nœud 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== Exigences d'inventaire

Vous devez disposer des éléments suivants pour collecter les données de stock :

* Adresse IP du serveur HCP
* Nom d'utilisateur et mot de passe en lecture seule pour le logiciel HCP et les privilèges homologues




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Hôte HCP | Adresse IP ou nom de domaine complet de l'hôte HCP 


| Port HCP | La valeur par défaut est 9090 


| ID utilisateur HCP | Nom d'utilisateur de l'hôte HCP. 


| Mot de passe HCP | Mot de passe utilisé pour l'hôte HCP. 


| Type d'authentification HCP | Choisissez HCP_LOCAL ou ACTIVE_DIRECTORY 
|===


== Configuration avancée

|===


| Champ | Description 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 60. 


| Intervalle d'interrogation des performances (s) | Intervalle entre les sondages de performances. La valeur par défaut est 900. 
|===
Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
