---
sidebar: sidebar 
permalink: task-configure-placement-group-failure-aws.html 
keywords: placement group, failure, HA single zone, app.conf, rollback, AWS 
summary: Cloud Volumes ONTAP utilise une liaison privée Azure pour les connexions aux comptes de stockage associés. Si nécessaire, vous pouvez désactiver les liens privés Azure et utiliser les terminaux de service. 
---
= Configurez la création de groupe de placement pour AWS HA Single AZ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP échoue et annule les nouveaux déploiements des configurations haute disponibilité AWS dans une même zone de disponibilité, à chaque fois que la création du groupe de placement échoue. Si nécessaire, vous pouvez forcer la réussite des déploiements en configurant des groupes de placement pour contourner le processus de restauration lorsque la création échoue.



== Présentation

Par défaut, les déploiements échouent et les retours arrière lorsqu'un groupe de placement échoue au processus de création d'un environnement de travail à zone de disponibilité unique haute disponibilité. La création du groupe de placement échoue également et rebascule si les deux nœuds Cloud Volumes ONTAP et l'instance de médiateur ne sont pas présents.

Vous pouvez contourner le processus de retour arrière chaque fois que la création du groupe de placement échoue et autoriser les déploiements à continuer en configurant le fichier app.conf. Lors de l'annulation du processus de restauration, les déploiements ont réussi et le système génère une notification indiquant que la création du groupe de placement a échoué avec un état incomplet.



=== Désactiver la restauration en cas d'échec du groupe de positionnement

Pour désactiver l'échec du groupe de placement, l'indicateur « rollback-on-placement-group-failure » doit être défini sur « false ».

.Étapes
. Utilisez SSH pour vous connecter à l'hôte du connecteur et connectez-vous.
. Accédez au répertoire suivant : /opt/application/netapp/cloudManager/docker_ocm/data
. Modifiez APP.conf en définissant la valeur du paramètre « rollback-on-placement-group-failure » sur « false » :
+
[listing]
----
{
    "occm" : {
        "aws" : {
            "rollback-on-placement-group-failure" : false
        }
    }
}
----
+

NOTE: Par défaut, le paramètre « rollback-on-placement-group-failure » est défini sur « vrai ».

. Enregistrez le fichier et déconnectez le connecteur.
+
Aucun redémarrage n'est requis.


