---
sidebar: sidebar 
permalink: task_config_cs_incloud.html 
keywords: Cloud, Storage, AWS, Cloud Volumes, Cloud ONTAP, firewall, VPC, Subnet, 
summary: 'Cloud Secure utilise des collecteurs de données pour collecter les données d"accès des fichiers et des utilisateurs à partir de terminaux.' 
---
= Configuration du Data Collector de Cloud Volumes ONTAP
:allow-uri-read: 


[role="lead"]
Cloud Secure utilise des collecteurs de données pour collecter les données d'accès des fichiers et des utilisateurs à partir de terminaux.



== Configuration du stockage Cloud Volumes ONTAP

Consultez la documentation de OnCommand Cloud Manager pour configurer une instance AWS à un seul nœud/haute disponibilité pour héberger l'agent Cloud Secure :https://docs.netapp.com/us-en/occm/index.html[]

Une fois la configuration terminée, suivre les étapes de configuration de votre SVM :https://docs.netapp.com/us-en/cloudinsights/task_add_collector_svm.html[]



== Configuration de l'ordinateur agent

Procédez comme suit pour configurer la machine à utiliser en tant qu'agent Cloud Secure :

.Étapes
. Connectez-vous à la console AWS, accédez à la page EC2-instances et sélectionnez _Launch instance_.
. Sélectionnez une ami RHEL ou CentOS avec la version appropriée, comme indiqué sur cette page :https://docs.netapp.com/us-en/cloudinsights/concept_cs_agent_requirements.html[]
. Sélectionnez le VPC et le sous-réseau dans lesquels réside l'instance de Cloud ONTAP.
. Sélectionnez _t2.XLarge_ (4 cpu virtuels et 16 Go de RAM) comme ressources allouées.
+
.. Créez l'instance EC2.


. Installez les packages Linux requis à l'aide du gestionnaire de package YUM :
+
.. Installez les packages Linux natifs _wget_ et _unzip_.






== Installez l'agent Cloud Secure

. Connectez-vous en tant qu'administrateur ou responsable de compte à votre environnement Cloud Insights.
. Accédez à Cloud Secure *Admin > collecteurs de données* et cliquez sur l'onglet *agents*.
. Cliquez sur *+Agent* et spécifiez RHEL comme plate-forme cible.
. Copiez la commande installation de l'agent.
. Collez la commande installation de l'agent dans l'instance RHEL EC2 à laquelle vous êtes connecté. Cela installe l'agent Cloud Secure, fournissant ainsi tous les link:concept_cs_agent_requirements.html["Conditions préalables de l'agent"] sont satisfaits.


Pour plus de détails, consultez le lien suivant : https://docs.netapp.com/us-en/cloudinsights/task_cs_add_agent.html#steps-to-install-agent
