---
sidebar: sidebar 
permalink: task_dc_emc_vplex.html 
keywords: data collector, VPLEX, EMC 
summary: Configuration du collecteur de données VPLEX. 
---
= Configuration du collecteur de données EMC VPLEX
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert les données d'inventaire et de performance des systèmes de stockage EMC VPLEX. Pour la configuration, le collecteur de données nécessite une adresse IP du serveur VPLEX et un compte de domaine de niveau administratif.


NOTE: La collecte des performances de Cloud Insights à partir de clusters VPLEX nécessite que le service d'archivage des performances soit opérationnel, afin de remplir les fichiers et journaux .CSV que Cloud Insights récupère via des copies de fichiers SCP. NetApp a observé que de nombreuses mises à niveau/station de gestion du firmware VPLEX ne seront pas opérationnelles. Les clients qui planifient de telles mises à niveau peuvent demander à Dell/EMC de manière proactive si leur mise à niveau prévue laissera cette fonctionnalité inutilisable, et, dans l'affirmative, comment peuvent-ils la réactiver afin de réduire les lacunes dans la visibilité des performances ? Le code de performances VPLEX de Cloud Insight évaluera à chaque interrogation si tous les fichiers attendus existent et s'ils sont correctement mis à jour. S'ils sont manquants ou obsolètes, Cloud Insights consigne les échecs de collecte de performances.



== Terminologie

Cloud Insight St acquiert les informations d'inventaire suivantes auprès du collecteur de données VPLEX. Pour chaque type d'actif acquis, la terminologie la plus utilisée pour ce bien est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Cluster | Stockage 


| Moteur | Nœud de stockage 


| Périphérique, extension du système | Pool de stockage interne 


| Volume virtuel | Volumétrie 


| Port frontal, port arrière | Port 


| Périphérique distribué | Synchronisation du stockage 


| Vue du stockage | Carte de volume, masque de volume 


| Volume de stockage | LUN interne 


| ITL | Chemin interne 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* Une adresse IP de VPLEX Management Console
* Compte de domaine de niveau administratif pour le serveur VPLEX
* Port 443 (HTTPS). Nécessite une connectivité sortante vers le port TCP 443 de la station de gestion VPLEX.
* Pour des performances optimales, le nom d'utilisateur et le mot de passe en lecture seule pour l'accès ssh/scp.
* Pour les performances, le port 22 est requis.




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP de VPLEX Management Console | Adresse IP ou nom de domaine complet de VPLEX Management Console 


| Nom d'utilisateur | Nom d'utilisateur pour la CLI VPLEX 


| Mot de passe | Mot de passe utilisé pour la CLI VPLEX 


| Adresse IP distante de performance | Adresse IP distante des performances de la console VPLEX Management Console 


| Nom d'utilisateur à distance de performance | Performance Nom d'utilisateur distant de VPLEX Management Console 


| Mot de passe de performance à distance | Mot de passe de performance à distance de VPLEX Management Console 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port de communication | Port utilisé pour la CLI VPLEX. La valeur par défaut est 443. 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 20 minutes. 


| Nombre de tentatives de connexion | La valeur par défaut est 3. 


| Intervalle d'interrogation des performances (s) | Intervalle entre les sondages de performances. La valeur par défaut est 600 secondes. 


| Nombre de tentatives | La valeur par défaut est 2. 
|===


== Dépannage

Certaines choses à essayer si vous rencontrez des problèmes avec ce collecteur de données :



==== Inventaire

[cols="2*"]
|===
| Problème : | Essayer : 


| Erreur : l'authentification de l'utilisateur a échoué. | Assurez-vous que vos informations d'identification pour ce périphérique sont correctes. 
|===


==== Performance

[cols="2*"]
|===
| Problème : | Essayer : 


| Erreur : les performances VPLEX pour la version inférieure à 5.3 ne sont pas prises en charge. | Mettez à niveau VPLEX vers 5.3 ou une version supérieure 


| Erreur : données collectées insuffisantes. | • Vérifiez l'horodatage de collecte dans le fichier journal et modifiez l'intervalle de vote en conséquence • attendez plus longtemps 


| Erreur : les fichiers journaux permanents ne sont pas mis à jour. | Veuillez contacter le support EMC pour activer la mise à jour des fichiers journaux permanents 


| Erreur : l'intervalle d'interrogation des performances est trop important. | Vérifiez l'horodatage de collecte dans le fichier journal ${logfile} et modifiez l'intervalle d'interrogation en conséquence 


| Erreur : l'adresse IP distante de performances de VPLEX Management Console n'est pas configurée. | Modifiez la source de données pour définir l'adresse IP de performance à distance de VPLEX Management Console. 


| Erreur : aucune donnée de performance signalée par le directeur | • Vérifiez que les moniteurs de performances du système fonctionnent correctement • Veuillez contacter le support EMC pour permettre la mise à jour des fichiers journaux du moniteur de performances du système 
|===
Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
