---
sidebar: sidebar 
permalink: task_dc_emc_ecs.html 
keywords: data collector, ecs, EMC 
summary: Configuration du collecteur de données ECS. 
---
= Configuration du collecteur de données EMC ECS
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert les données d'inventaire et de performance des systèmes de stockage EMC ECS. Pour la configuration, le collecteur de données nécessite une adresse IP du serveur ECS et un compte de domaine de niveau administratif.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données ECS. Pour chaque type d'actif acquis, la terminologie la plus utilisée pour ce bien est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Cluster | Stockage 


| Locataire | Pool de stockage 


| Godet | Volume interne 


| Disque | Disque 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* Une adresse IP de la console de gestion ECS
* Compte de domaine de niveau administratif pour le système ECS
* Port 443 (HTTPS). Nécessite une connectivité sortante vers le port TCP 443 du système ECS.
* Pour des performances optimales, le nom d'utilisateur et le mot de passe en lecture seule pour l'accès ssh/scp.
* Pour les performances, le port 22 est requis.




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Hôte ECS | Adresse IP ou nom de domaine complet du système ECS 


| Port hôte ECS | Port utilisé pour la communication avec l'hôte ECS 


| ID fournisseur ECS | ID fournisseur pour ECS 


| Mot de passe | Mot de passe utilisé pour ECS 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | La valeur par défaut est 360 minutes. 
|===


== Dépannage

Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
