---
sidebar: sidebar 
permalink: task_dc_emc_vnx_file.html 
keywords: data collector, Celerra, EMC, DELL, VNX File 
summary: Configuration du collecteur de données DELL EMC Celerra. 
---
= Collecteur de données DELL EMC VNX File (anciennement Celerra Unified Storage System)
:allow-uri-read: 


[role="lead"]
Ce collecteur de données acquiert les informations d'inventaire à partir du système de stockage de fichiers VNX. Pour la configuration, ce collecteur de données nécessite l'adresse IP des processeurs de stockage ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes à partir du collecteur de données VNX File. Pour chaque type de bien acquis par Cloud Insights, la terminologie la plus utilisée pour ce bien est présentée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Celerra Network Server/Celerra Storage Pool | Pool de stockage 


| Système de fichiers | Volume interne 


| Data Mover | Contrôleur 


| Système de fichiers monté sur un mécanisme de déplacement des données | Partage de fichiers 


| Exports CIFS et NFS | Partagez 


| Volume de disque | LUN interne 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

Vous devez disposer des éléments suivants pour configurer ce collecteur de données :

* L'adresse IP du processeur de stockage
* Nom d'utilisateur et mot de passe en lecture seule
* Port SSH 22




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse IP du fichier VNX | Adresse IP ou nom de domaine complet du périphérique VNX File 


| Nom d'utilisateur | Nom utilisé pour se connecter au périphérique VNX File 


| Mot de passe | Mot de passe utilisé pour se connecter au périphérique VNX File 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (minutes) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 20 minutes. 
|===


== Dépannage

Certaines choses à essayer si vous rencontrez des problèmes avec ce collecteur de données :



==== Inventaire

[cols="2*"]
|===
| Problème : | Essayer : 


| Erreur : impossible de continuer pendant la mise à jour DART en cours | Solution possible : interrompre le collecteur de données et attendre la fin de la mise à niveau du DART avant de tenter une autre demande d'acquisition. 
|===
Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
