---
sidebar: sidebar 
permalink: task-connect-lun.html 
keywords: lun, connect lun, iscsi lun, target iqn, iqn 
summary: 'Lorsque vous créez un volume iSCSI, BlueXP crée automatiquement un LUN pour vous. Nous avons simplifié la gestion en créant un seul LUN par volume, ce qui n"implique aucune gestion. Une fois le volume créé, utilisez l"IQN pour vous connecter à la LUN à partir de vos hôtes.' 
---
= Connectez une LUN à un hôte
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lorsque vous créez un volume iSCSI, BlueXP crée automatiquement un LUN pour vous. Nous avons simplifié la gestion en créant un seul LUN par volume, ce qui n'implique aucune gestion. Une fois le volume créé, utilisez l'IQN pour vous connecter à la LUN à partir de vos hôtes.

Notez ce qui suit :

* La gestion automatique de la capacité de BlueXP ne s'applique pas aux LUN. Lorsque BlueXP crée un LUN, il désactive la fonction Autogrow.
* Vous pouvez créer des LUN supplémentaires depuis System Manager ou l'interface de ligne de commandes.


.Étapes
. Dans le menu de navigation de gauche, sélectionnez *stockage > Canvas*.
. Sur la page Canevas, double-cliquez sur l'environnement de travail Cloud Volumes ONTAP sur lequel vous souhaitez gérer les volumes.
. Dans l'environnement de travail, cliquez sur l'onglet *volumes*.
. Dans l'onglet volumes, accédez au titre du volume souhaité, puis cliquez sur *gérer le volume* pour accéder au panneau de droite gérer les volumes.
. Cliquez sur *IQN cible*.
. Cliquez sur *Copy* pour copier le nom IQN.
. Configurez une connexion iSCSI de l'hôte vers le LUN.
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-rhel-cg/GUID-15E8C226-BED5-46D0-BAED-379EA4311340.html["Configuration iSCSI express ONTAP 9 pour Red Hat Enterprise Linux : démarrage des sessions iSCSI avec la cible"^]
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.exp-iscsi-cpg/GUID-857453EC-90E9-4AB6-B543-83827CF374BF.html["Configuration iSCSI express de ONTAP 9 pour Windows : démarrage des sessions iSCSI avec la cible"^]
** https://docs.netapp.com/us-en/ontap-sanhost/["Configuration de l'hôte SAN ONTAP"^]



