---
sidebar: sidebar 
permalink: task_isolate_root_volume.html 
summary: 'Lorsque vous recherchez une densité d"E/S élevée, vous voulez exclure les volumes racine.' 
keywords: NetApp, root volume, high I/O, 
---
= Les rapports de densité d'E/S décrivent uniquement les volumes de données internes
:allow-uri-read: 


[role="lead"]
Le volume racine de NetApp contient des répertoires et des fichiers de configuration pour la gestion du système de stockage. Lorsque vous recherchez une densité d'E/S élevée, vous voulez exclure ces volumes racine.

Lors de la surveillance de votre environnement, il est plus important de déterminer quels volumes de données internes produisent des chiffres de densité d'E/S élevés. Pour identifier avec précision uniquement les volumes de données, vous devez isoler les volumes internes NetApp des requêtes utilisées pour surveiller la densité des E/S.

Ce guide explique comment identifier facilement les agrégats racine NetApp, les isoler des résultats des requêtes de volume internes et créer des règles qui excluent tous les nouveaux agrégats racine NetApp lors de leur ajout au système. Les fonctions Insight suivantes permettent de s'assurer que vos rapports de densité d'E/S sont issus des volumes de données internes :

* Une requête est créée afin d'identifier tous les agrégats racine NetApp surveillés par Insight.
* Une annotation est attribuée à chacun des agrégats racines NetApp.
* Une règle d'annotation est créée pour appliquer cette annotation aux nouveaux agrégats racine NetApp.


Les étapes de ce guide peuvent également être appliquées aux systèmes de stockage d'autres fournisseurs. Vous devez identifier les volumes contenant des répertoires et des fichiers de configuration pour gérer le système de stockage et utiliser des étapes similaires pour exclure ces volumes.



== Création d'une requête permettant d'identifier les agrégats racine NetApp dans votre environnement

Les requêtes fournissent une recherche granulaire, en fonction des critères sélectionnés par l'utilisateur. Une requête vous permet de rechercher des volumes internes dans votre environnement contenant l'agrégat racine NetApp.

. Étapes
. Créer une requête pour identifier les agrégats racine NetApp dans votre environnement : cliquez sur *Queries > New Query > Select Resource Type* (?)
. Cliquez sur *pool de stockage*
. Entrer le nom de l'agrégat root
+
Cet exemple utilise "aggr0" pour le nom. Lors de la création d'un agrégat, seules les exigences suivantes doivent être respectées pour ce nom : .. Il doit commencer par une lettre ou un trait de soulignement (_). .. Il ne peut contenir que des lettres, des chiffres et des traits de soulignement. .. Elle peut comporter 250 caractères maximum. Dans la plupart des cas, l'agrégat est nommé aggr0, aggr_0 ou quelque chose de similaire. Cela peut impliquer un processus itératif pour identifier tous les agrégats racines NetApp de votre environnement.

. Cliquez sur *Enregistrer* et entrez un nom pour la nouvelle requête.
+
Comme mentionné précédemment, il peut s'agir d'un processus itératif et nécessite plusieurs requêtes pour identifier tous les agrégats racines NetApp.





== Créez une annotation pour les volumes racine renvoyés par vos requêtes

Les annotations sont des notes spécialisées que vous attribuez à vos ressources, ce qui vous permet de filtrer les ressources par leurs annotations. Cette annotation vous permettra d'identifier les agrégats NetApp racine dans votre environnement et de vérifier qu'ils ne sont pas inclus dans un rapport spécifique.

.Avant de commencer
Vous devez avoir identifié tous les agrégats racine à exclure du rapport « densité d'E/S élevée ».

.Étapes
. Dans le menu Cloud Insights, cliquez sur *gérer > Annotations*
. Cliquez sur *Ajouter*
+
.. Entrez le nom de l'annotation : *RootAggr*
.. Entrez une description de l'annotation : *Supprimer l'agrégat racine du rapport "densité d'E/S élevée"*
.. Saisissez le type d'annotation : *Boolean*


. Cliquez sur *Enregistrer*




== Créez une règle d'annotation pour automatiser l'exclusion des agrégats spécifiques de votre rapport de densité d'E/S.

Au lieu d'appliquer manuellement des annotations à des ressources individuelles, vous pouvez appliquer automatiquement des annotations à plusieurs ressources à l'aide de règles d'annotation. Les règles d'annotation sont basées sur les requêtes que vous créez et lorsqu'elles sont exécutées sur le système, elles ajoutent de nouvelles ressources à des ensembles de ressources existants. Lorsque ces ensembles d'actifs sont exclus d'un rapport, les nouveaux actifs sont également automatiquement exclus.

.Avant de commencer
Vous devez avoir créé et enregistré une requête qui identifie les agrégats racine NetApp que vous avez identifiés dans votre environnement. . Étapes . Dans la barre d'outils Cloud Insights, cliquez sur *gérer > règles d'annotation* . Cliquez sur *Ajouter*

+ la boîte de dialogue Ajouter une règle s'affiche : .. Dans la zone Nom , entrez un nom unique qui décrit la règle : *"RootAggrExclude"* .. Cliquez sur requête et sélectionnez la requête à utiliser par Insight pour appliquer la règle d'annotation à : *"Aggregate0"* .. Cliquez sur Annotation et sélectionnez : *"exclusion d'agg racine"* .. Cliquez sur *valeur* et saisissez *vrai*
