---
sidebar: sidebar 
permalink: task_device_resolution_rules.html 
keywords: Automatic, AR, AHR, Host, automatic device resolution 
summary: 'La résolution des périphériques vous permet de suivre avec précision les performances et l"inventaire de votre environnement.' 
---
= Règles de résolution du périphérique
:allow-uri-read: 


[role="lead"]
Vous créez des règles de résolution des périphériques pour identifier les hôtes, le stockage et les bandes qui ne sont pas automatiquement identifiés actuellement par Cloud Insights. Les règles que vous créez identifient les périphériques actuellement dans votre environnement et identifient également les périphériques similaires ajoutés à votre environnement.



== Création de règles de résolution de périphérique

Lorsque vous créez des règles, vous commencez par identifier la source des informations sur lesquelles la règle s'exécute, la méthode utilisée pour extraire des informations et si la recherche DNS est appliquée aux résultats de la règle.

[cols="2*"]
|===


| Source utilisée pour identifier le périphérique | * Alias SRM pour les hôtes * alias de stockage contenant un nom d'hôte ou de bande intégré * alias de commutateur contenant un nom d'hôte ou de bande intégré * noms de zone contenant un nom d'hôte intégré 


| Méthode utilisée pour extraire le nom du périphérique de la source | * Tel qu'il est (extrait un nom d'un SRM) * Delimters * expressions régulières 


| Recherche DNS | Indique si vous utilisez DNS pour vérifier le nom d'hôte 
|===
Vous créez des règles dans l'onglet règles de résolution automatique. Les étapes suivantes décrivent le processus de création de règles.

.Procédure
. Cliquez sur *gérer > résolution du périphérique*
. Dans l'onglet *règles de résolution automatique*, cliquez sur *+ règle hôte* ou *+ règle bande*.
+
L'écran *règle de résolution* s'affiche.

+

NOTE: Cliquez sur le lien _Afficher les critères de correspondance_ pour obtenir de l'aide et des exemples pour créer des expressions régulières.

. Dans la liste *Type*, sélectionnez le périphérique à identifier.
+
Vous pouvez sélectionner _Host_ ou _Tape_.

. Dans la liste *Source*, sélectionnez la source à utiliser pour identifier l'hôte.
+
Selon la source que vous avez choisie, Cloud Insights affiche la réponse suivante :

+
.. *Zones* répertorie les zones et WWN qui doivent être identifiés par Cloud Insights.
.. *SRM* liste les alias non identifiés qui doivent être identifiés par Cloud Insights
.. *Alias de stockage* répertorie les alias de stockage et WWN qui doivent être identifiés par Cloud Insights
.. *Alias de commutateur* répertorie les alias de commutateur qui doivent être identifiés par Cloud Insights


. Dans la liste *méthode*, sélectionnez la méthode à utiliser pour identifier l'hôte.
+
|===


| Source | Méthode 


| SRM | Tout comme les délimiteurs, expressions régulières 


| Alias de stockage | Délimiteurs, expressions régulières 


| Changer d'alias | Délimiteurs, expressions régulières 


| Zones | Délimiteurs, expressions régulières 
|===
+
** Les règles utilisant des délimiteurs nécessitent les délimiteurs et la longueur minimale du nom d'hôte. La longueur minimale du nom d'hôte correspond au nombre de caractères que Cloud Insights doit utiliser pour identifier un hôte. Cloud Insights effectue des recherches DNS uniquement pour les noms d'hôtes qui sont aussi longs ou plus.
+
Pour les règles utilisant des délimitateurs, la chaîne d'entrée est tokenisée par le délimiteur et une liste de candidats de noms d'hôte est créée en faisant plusieurs combinaisons du jeton adjacent. La liste est ensuite triée, la plus grande à la plus petite. Par exemple, pour un sring d'entrée de _vipsnq03_hba3_emc3_12ep0_, la liste se traduit par ce qui suit :

+
*** vipsnq03_hba3_emc3_12ep0
*** vipsnq03_hba3_emc3
*** hba3 emc3_12ep0
*** vipsnq03_hba3
*** emc3_12ep0
*** hba3_emc3
*** vipsnq03
*** 12ep0
*** emc3
*** hba3


** Les règles utilisant des expressions régulières nécessitent une expression régulière, le format et la sélection de sensibilité des cas.


. Cliquez sur *Exécuter AR* pour exécuter toutes les règles ou cliquez sur la flèche vers le bas du bouton pour exécuter la règle que vous avez créée (et toutes les autres règles créées depuis la dernière exécution complète d'AR).
+
Les résultats de l'exécution de la règle sont affichés dans l'onglet *FC Identify*.





== Démarrage d'une mise à jour automatique de la résolution des périphériques

Une mise à jour de la résolution du périphérique valide les modifications manuelles qui ont été ajoutées depuis la dernière exécution de la résolution automatique complète du périphérique. L'exécution d'une mise à jour peut être utilisée pour valider et exécuter uniquement les nouvelles entrées manuelles apportées à la configuration de résolution de périphérique. Aucune résolution complète du périphérique n'est exécutée.

.Procédure
. Connectez-vous à l'interface utilisateur Web de Cloud Insights.
. Cliquez sur *gérer > résolution du périphérique*
. Dans l'écran *Device Resolution*, cliquez sur la flèche vers le bas du bouton *Run AR*.
. Cliquez sur *Update* pour lancer la mise à jour.




== Identification manuelle assistée par des règles

Cette fonction est utilisée dans des cas particuliers où vous souhaitez exécuter une règle spécifique ou une liste de règles (avec ou sans réorganisation unique) pour résoudre des hôtes inconnus, des périphériques de stockage et de bande.

.Avant de commencer
Vous avez un certain nombre de périphériques qui n'ont pas été identifiés et vous disposez également de plusieurs règles qui ont identifié d'autres périphériques avec succès.


NOTE: Si votre source ne contient qu'une partie d'un nom d'hôte ou de périphérique, utilisez une règle d'expression régulière et formatez-la pour ajouter le texte manquant.

.Procédure
. Connectez-vous à l'interface utilisateur Web de Cloud Insights.
. Cliquez sur *gérer > résolution du périphérique*
. Cliquez sur l'onglet *Fibre Channel Identify*.
+
Le système affiche les périphériques avec leur état de résolution.

. Sélectionnez plusieurs périphériques non identifiés.
. Cliquez sur *actions groupées* et sélectionnez *définir la résolution de l'hôte* ou *définir la résolution de la bande*.
+
Le système affiche l'écran identifier qui contient une liste de toutes les règles qui ont identifié les périphériques avec succès.

. Modifiez l'ordre des règles en un ordre qui répond à vos besoins.
+
L'ordre des règles est modifié dans l'écran identifier, mais ne sont pas modifiés globalement.

. Sélectionnez la méthode qui répond à vos besoins.


Cloud Insights exécute le processus de résolution de l'hôte dans l'ordre dans lequel les méthodes apparaissent, en commençant par celles en haut.

Lorsque des règles s'appliquent, les noms de règles s'affichent dans la colonne règles et sont identifiés comme étant manuels.

En savoir plus :link:task_device_resolution_fibre_channel.html["Résolution de périphérique Fibre Channel"]
link:task_device_resolution_ip.html["Résolution de périphérique IP"]
link:task_device_resolution_preferences.html["Définition des préférences de résolution du périphérique"]
