---
sidebar: sidebar 
permalink: task_dc_ibm_cleversafe.html 
keywords: data collector, IBM Cleversafe 
summary: Configuration du collecteur de données IBM Cleversafe. 
---
= Collecteur de données IBM Cleversafe
:allow-uri-read: 


[role="lead"]
Cloud Insights utilise ce collecteur de données pour détecter les données d'inventaire et de performance des systèmes de stockage IBM Cleversafe.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données IBM Cleversafe. Pour chaque type de bien acquis par Cloud Insights, la terminologie la plus utilisée pour ce bien est présentée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Pool de stockage | Pool de stockage 


| Conteneur | Volume interne 


| Conteneur | Partage de fichiers 


| Partage NFS | Partagez 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

* L'adresse IP des services de données externes pour le cluster
* Nom d'utilisateur et mot de passe administrateur
* Orifice 9440




== Configuration

[cols="2*"]
|===
| Champ | Description 


| IP Manager ou nom d'hôte | Adresse IP ou nom d'hôte du nœud de gestion 


| Nom d'utilisateur | Nom d'utilisateur du compte utilisateur avec le rôle super utilisateur ou administrateur système 


| Mot de passe | Mot de passe du compte utilisateur avec le rôle super utilisateur ou administrateur système 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. 


| Délai d'expiration de la connexion HTTP (sec) | Délai d'attente HTTP en secondes. 
|===


== Dépannage

Pour plus d'informations sur ce Data Collector, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
