---
sidebar: sidebar 
permalink: task_dc_na_7mode.html 
keywords: data collector, 7-mode, NetApp 
summary: Configuration du collecteur de données NetApp 7-mode. 
---
= Collecteur de données NetApp Data ONTAP 7-mode
:allow-uri-read: 


[role="lead"]
Pour les systèmes de stockage qui utilisent le logiciel Data ONTAP 7-mode, vous utilisez le collecteur de données 7-mode qui utilise l'interface de ligne de commandes pour obtenir des données de capacité et de performances.



== Terminologie

Cloud Insights acquiert les informations d'inventaire suivantes auprès du collecteur de données 7-mode NetApp. Pour chaque type d'actif acquis, la terminologie la plus utilisée pour ce bien est indiquée. Lors de l'affichage ou du dépannage de ce collecteur de données, gardez la terminologie suivante à l'esprit :

[cols="2*"]
|===
| Terme du fournisseur/modèle | Terme Cloud Insights 


| Disque | Disque 


| Groupe RAID | Groupe de disques 


| Fichier | Stockage 


| Fichier | Nœud de stockage 


| Agrégat | Pool de stockage 


| LUN | Volumétrie 


| Volumétrie | Volume interne 
|===
Remarque : il s'agit uniquement de mappages terminologiques communs et peuvent ne pas représenter tous les cas pour ce collecteur de données.



== De formation

Vous devez disposer des éléments suivants pour configurer et utiliser ce collecteur de données :

* Les adresses IP du contrôleur de stockage FAS et du partenaire.
* Orifice 443
* Nom d'utilisateur et mot de passe personnalisés de niveau administrateur pour les contrôleurs et les contrôleurs partenaires, avec les fonctionnalités suivantes pour 7-mode :
+
** « api-* » : utilisez-le pour permettre à OnCommand Insight d'exécuter toutes les commandes de l'API de stockage NetApp.
** « Login-http-admin » : utilisez ce pour permettre à OnCommand Insight de se connecter au stockage NetApp via HTTP.
** « Security-api-vfiler » : utilisez cette option pour permettre à OnCommand Insight d'exécuter les commandes de l'API de stockage NetApp et de récupérer les informations relatives à l'unité vFiler.
** « cli-options » : permet de lire les options du système de stockage.
** cli-lun : accédez à ces commandes pour gérer les LUN. Affiche le statut (chemin de LUN, taille, état en ligne/hors ligne et état partagé) de la LUN ou classe de LUN donnée.
** « cli-df » : utilisez ce système pour afficher l'espace disque disponible.
** « cli-ifconfig » : utilisez-le pour afficher les interfaces et les adresses IP.






== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse du système de stockage | Adresse IP ou nom de domaine complet pour le système de stockage NetApp 


| Nom d'utilisateur | Nom d'utilisateur du système de stockage NetApp 


| Mot de passe | Mot de passe du système de stockage NetApp 


| Adresse du partenaire de haute disponibilité dans le Cluster | Adresse IP ou nom de domaine complet pour le partenaire de haute disponibilité 


| Nom d'utilisateur du partenaire de haute disponibilité dans le cluster | Nom d'utilisateur du partenaire HA 


| Mot de passe du serveur de fichiers du partenaire HA dans le cluster | Mot de passe du partenaire HA 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Intervalle d'interrogation des stocks (min) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 20 minutes. 


| Type de connexion | HTTPS ou HTTP, affiche également le port par défaut 


| Remplacer le port de connexion | Si ce champ est vide, utilisez le port par défaut dans le champ Type de connexion, sinon entrez le port de connexion à utiliser 


| Intervalle d'interrogation des performances (s) | Intervalle entre les sondages de performances. La valeur par défaut est 300 secondes. 
|===


== Connexion des systèmes de stockage

Comme alternative à l'utilisation de l'utilisateur d'administration par défaut pour ce collecteur de données, vous pouvez configurer un utilisateur avec des droits d'administration directement sur les systèmes de stockage NetApp. Ainsi, ce collecteur de données peut acquérir des données à partir des systèmes de stockage NetApp.

Pour se connecter aux systèmes de stockage NetApp, l'utilisateur, qui est spécifié lors de l'acquisition du filer principal (là où il existe le système de stockage), doit respecter les conditions suivantes :

* L'utilisateur doit se trouver sur vfiler0 (filer racine/pFiler).
+
Les systèmes de stockage sont acquis lors de l'acquisition du filer principal.

* Les commandes suivantes définissent les fonctions de rôle utilisateur :
+
** « api-* » : utilisez-le pour permettre à Cloud Insights d'exécuter toutes les commandes de l'API de stockage NetApp.
+
Cette commande est nécessaire pour utiliser le ZAPI.

** « Login-http-admin » : utilisez ce pour permettre à Cloud Insights de se connecter au stockage NetApp via HTTP. Cette commande est nécessaire pour utiliser le ZAPI.
** « Security-api-vfiler » : utilisez cette option pour permettre à Cloud Insights d'exécuter les commandes de l'API de stockage NetApp et de récupérer les informations relatives à l'unité vFiler.
** « cli-options » : pour la commande « options » et utilisée pour les licences IP du partenaire et activées.
** cli-lun : accédez à cette commande pour gérer les LUN. Affiche le statut (chemin de LUN, taille, état en ligne/hors ligne et état partagé) de la LUN ou classe de LUN donnée.
** « cli-df » : pour les commandes df –s », « df -r » et « df -A -r » et l'espace utilisé pour afficher l'espace disponible.
** « cli-ifconfig » : pour la commande « ifconfig -a » et utilisée pour obtenir l'adresse IP du filer.
** « cli-rdfile » : pour la commande « rdfile /etc/netgroup » et utilisée pour obtenir des netgroups.
** CLI-date : pour la commande « date » et utilisée pour obtenir des dates complètes pour la copie Snapshot.
** CLI-snap : pour la commande « snap list » et utilisée pour obtenir les copies Snapshot.




Si vous ne disposez pas d'autorisations CLI-date ou CLI-snap, l'acquisition peut être terminée, mais les copies Snapshot ne sont pas signalées.

Pour acquérir une source de données 7-mode avec succès et ne générer aucun avertissement sur le système de stockage, définissez les rôles à l'aide de l'une des chaînes de commandes suivantes. La deuxième chaîne répertoriée ici est une version simplifiée de la première :

* login-http-admin,api-*,security-api-vfile,cli-rdfile,cli-options,cli-df,cli-lun,cli-ifconfig,cli-date,cli-snap,_
* login-http-admin,api-*,security-api-vfile,cli-




== Dépannage

Certaines choses à essayer si vous rencontrez des problèmes avec ce collecteur de données :



==== Inventaire

[cols="2*"]
|===
| Problème : | Essayer : 


| Réception 401 réponse HTTP ou 13003 code d'erreur ZAPI et ZAPI renvoie “privilèges insuffisants” ou “non autorisés pour cette commande” | Vérifiez le nom d'utilisateur et le mot de passe, ainsi que les privilèges/autorisations utilisateur. 


| Erreur "échec de l'exécution de la commande" | Vérifiez si l'utilisateur dispose de l'autorisation suivante sur le terminal : • api-* • cli-date • cli-df • cli-ifconfig • cli-lun • cli-Operations • cli-rdfile • cli-snap • login-http-admin • Security-api-vfiler vérifie également si la version ONTAP est prise en charge par Cloud Insights et vérifie si les informations d'identification utilisées pour le périphérique correspondent 


| La version du cluster est < 8.1 | La version minimale prise en charge par le cluster est 8.1. Passez à la version minimale prise en charge. 


| ZAPI renvoie « le rôle de cluster n'est pas Cluster_mgmt LIF ». | L'au doit communiquer avec l'IP de gestion de cluster. Vérifiez l'adresse IP et remplacez-la par une autre adresse IP si nécessaire 


| Erreur : "les filers 7 mode ne sont pas pris en charge" | Cela peut se produire si vous utilisez ce collecteur de données pour découvrir le filer 7 mode. Remplacez l'IP par un filer cdot. 


| La commande ZAPI échoue après une nouvelle tentative | Problème de communication au avec le cluster. Vérifiez le réseau, le numéro de port et l'adresse IP. L'utilisateur doit également essayer d'exécuter une commande à partir de la ligne de commande à partir de l'ordinateur au. 


| Echec de la connexion à ZAPI | Vérifiez la connectivité IP/port et activez la configuration ZAPI. 


| Echec de la connexion à ZAPI via HTTP | Vérifiez si le port ZAPI accepte le texte en clair. Si l'au tente d'envoyer du texte en texte clair vers une socket SSL, la communication échoue. 


| La communication échoue avec SSLException | Au tente d'envoyer SSL vers un port en texte clair sur un filer. Vérifiez si le port ZAPI accepte SSL ou utilise un autre port. 


| Autres erreurs de connexion : la réponse ZAPI a le code d’erreur 13001, “la base de données n’est pas ouverte” le code d’erreur ZAPI est 60 et la réponse contient “l’API n’a pas terminé à temps” la réponse ZAPI contient “initialize_session() retourné environnement NULL” le code d’erreur ZAPI est 14007 et la réponse contient “noeud n’est pas sain” | Vérifiez le réseau, le numéro de port et l'adresse IP. L'utilisateur doit également essayer d'exécuter une commande à partir de la ligne de commande à partir de l'ordinateur au. 


| Erreur d'expiration de socket avec ZAPI | Vérifiez la connectivité du filer et/ou augmentez le délai d'expiration. 


| “Les clusters C mode ne sont pas pris en charge par la source de données 7 mode” | Vérifiez l'IP et remplacez l'IP par un cluster 7 mode. 


| Erreur « échec de la connexion à vFiler » | Vérifiez que les fonctionnalités utilisateur acquises incluent les éléments suivants au minimum : api-* Security-api-vfiler login-http-admin Confirmez que le filer exécute la version minimale de ONTAPI version 1.7. 
|===
Pour plus d'informations, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
