---
sidebar: sidebar 
permalink: task_create_annotation.html 
keywords: annotations, annotation rules, manual annotations, 
summary: Comment créer une annotation. 
---
= Utilisation d'annotations
:allow-uri-read: 


[role="lead"]
Vous créez des annotations et vous les attribuez aux ressources que vous surveillez. Ces annotations sont des notes qui fournissent des informations sur une ressource, telles que l'emplacement physique, la fin de vie, le niveau de stockage ou les niveaux de service de volume.



== Définition des annotations

Ces annotations vous permettent d'ajouter des données personnalisées spécifiques à l'entreprise qui correspondent aux ressources de votre entreprise. Alors que Cloud Insights fournit un ensemble d'annotations par défaut, telles que le cycle de vie des ressources (date d'anniversaire ou fin de vie), la création ou l'emplacement du data Center et le niveau, vous pouvez afficher les données d'autres manières.

Les données contenues dans des annotations personnalisées complètent les données déjà recueillies sur les périphériques, telles que le fabricant du commutateur, le nombre de ports et les statistiques de performance. Les données que vous ajoutez à l'aide d'annotations ne sont pas découvertes par Cloud Insights.

.Avant de commencer
* Répertoriez toute terminologie de l'industrie à laquelle les données d'environnement doivent être associées.
* Répertorier la terminologie d'entreprise à laquelle les données d'environnement doivent être associées.
* Identifiez tout type d'annotation par défaut que vous pouvez utiliser.
* Identifiez les annotations personnalisées que vous devez créer. Vous devez créer l'annotation pour pouvoir l'affecter à une ressource.


Procédez comme suit pour créer une annotation.

.Étapes
. Dans le menu Cloud Insights, cliquez sur *gérer > Annotations*
. Cliquez sur *+ Annotation* pour créer une nouvelle annotation.
. Entrez un nom, une description et un type pour la nouvelle annotation.
+
Par exemple, entrez ce qui suit pour créer une annotation texte qui définit l'emplacement physique d'une ressource dans Data Center 4 :

+
** Saisissez un nom pour l'annotation, tel que « emplacement »
** Saisissez une description de l'annotation, telle que « l'emplacement physique est Data Center 4 ».
** Entrez le type d'annotation, tel que « texte ».






== Affectation manuelle d'annotations aux ressources

L'affectation d'annotations aux ressources vous permet de trier, de regrouper et de générer des rapports sur les ressources de manière pertinente pour votre entreprise. Bien que vous puissiez attribuer automatiquement des annotations à des ressources d'un type particulier à l'aide de règles d'annotation, vous pouvez affecter des annotations à une ressource individuelle à l'aide de sa page de contenu.

.Avant de commencer
* Vous devez avoir créé l'annotation que vous souhaitez attribuer.


.Étapes
. Connectez-vous à votre environnement Cloud Insights.
. Localisez la ressource à laquelle vous souhaitez appliquer l'annotation.
+
** Vous pouvez localiser les ressources en effectuant une requête, en choisissant un widget dasoard ou en effectuant une recherche. Une fois que vous avez trouvé la ressource souhaitée, cliquez sur le lien pour ouvrir la page d'accueil de la ressource.


. Sur la page ressource, dans la section données utilisateur, cliquez sur *+ Annotation*.
. La boîte de dialogue Ajouter une annotation s'affiche.
. Sélectionnez une annotation dans la liste.
. Cliquez sur valeur et effectuez l'une des opérations suivantes, en fonction du type d'annotation que vous avez sélectionné :
+
** Si le type d'annotation est liste, date ou booléen, sélectionnez une valeur dans la liste.
** Si le type d'annotation est texte, saisissez une valeur.


. Cliquez sur *Enregistrer*.


Si vous souhaitez modifier la valeur de l'annotation après l'avoir affectée, cliquez sur le champ d'annotation et sélectionnez une autre valeur. Si l'annotation est de type liste pour laquelle l'option _Ajouter de nouvelles valeurs sur Fly_ est sélectionnée, vous pouvez saisir une nouvelle valeur en plus de la sélection d'une valeur existante.



== Affectation d'annotations à l'aide de règles d'annotation

Pour attribuer automatiquement des annotations aux ressources en fonction des critères que vous définissez, vous devez configurer des règles d'annotation. Cloud Insights attribue les annotations aux ressources en fonction de ces règles. Cloud Insights propose également deux règles d'annotation par défaut, que vous pouvez modifier en fonction de vos besoins ou supprimer si vous ne souhaitez pas les utiliser.



=== Création de règles d'annotation

Au lieu d'appliquer manuellement des annotations à des ressources individuelles, vous pouvez appliquer automatiquement des annotations à plusieurs ressources à l'aide de règles d'annotation. Les annotations définies manuellement sur une page de ressource individuelle ont priorité sur les annotations basées sur des règles lors de l'évaluation par Insight des règles d'annotation.

.Avant de commencer
Vous devez avoir créé une requête pour la règle d'annotation.

.Description de la tâche
Bien que vous puissiez modifier les types d'annotation lors de la création des règles, vous devez avoir défini les types à l'avance.

.Étapes
. Cliquez sur *gérer > règles d'annotation*
+
La page règles d'annotation affiche la liste des règles d'annotation existantes.

. Cliquez sur *+ Ajouter*.
. Procédez comme suit :
+
.. Dans la zone *Nom*, entrez un nom unique qui décrit la règle.
+
Ce nom apparaît dans la page règles d'annotation.

.. Cliquez sur *Query* et sélectionnez la requête utilisée pour appliquer l'annotation aux ressources.
.. Cliquez sur *Annotation* et sélectionnez l'annotation que vous souhaitez appliquer.
.. Cliquez sur *valeur* et sélectionnez une valeur pour l'annotation.
+
Par exemple, si vous choisissez anniversaire comme annotation, vous spécifiez une date pour la valeur.

.. Cliquez sur *Enregistrer*
.. Cliquez sur *Exécuter toutes les règles* si vous souhaitez exécuter toutes les règles immédiatement ; sinon, les règles sont exécutées à un intervalle planifié régulièrement.



