---
sidebar: sidebar 
permalink: task_dc_emc_recoverpoint.html 
keywords: data collector, RecoverPoint, EMC, DELL 
summary: Configuration DU collecteur de données DELL EMC RecoverPoint. 
---
= Collecteur de données Dell EMC RecoverPoint
:allow-uri-read: 


[role="lead"]
Le collecteur de données EMC RecoverPoint rassemble les informations d'inventaire à partir du stockage EMC RecoverPoint. Pour la configuration, le collecteur de données nécessite l'adresse IP des processeurs de stockage ainsi qu'un nom d'utilisateur et un mot de passe en lecture seule.

Le collecteur de données EMC RecoverPoint rassemble les relations de réplication volume-volume que RecoverPoint coordonne sur les autres matrices de stockage. Cloud Insights représente une matrice de stockage pour chaque cluster RecoverPoint et collecte les données d'inventaire pour les nœuds et les ports de stockage de ce cluster. Aucune donnée de volume ou de pool de stockage n'est collectée.



== De formation

Les informations suivantes sont requises pour configurer ce collecteur de données :

* Adresse IP ou nom de domaine complet du processeur de stockage
* Nom d'utilisateur et mot de passe en lecture seule
* Accès à l'API REST via le port 443




== Configuration

[cols="2*"]
|===
| Champ | Description 


| Adresse de RecoverPoint | Adresse IP ou nom de domaine complet du cluster RecoverPoint 


| Nom d'utilisateur | Nom d'utilisateur du cluster RecoverPoint 


| Mot de passe | Mot de passe utilisé pour le cluster RecoverPoint 
|===


== Configuration avancée

[cols="2*"]
|===
| Champ | Description 


| Port TCP | Port TCP utilisé pour se connecter au cluster RecoverPoint 


| Intervalle d'interrogation des stocks (minutes) | Intervalle entre les sondages d'inventaire. La valeur par défaut est 20 minutes. 


| Clusters exclus | Liste séparée par des virgules d'ID ou de noms de cluster à exclure lors de l'interrogation. 
|===


== Dépannage

Pour plus d'informations sur ce Data Collector, consultez le link:concept_requesting_support.html["Assistance"] ou dans le link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Matrice de prise en charge du Data Collector"].
